{ ... }: {
  # Asgard — books: Audiobookshelf (the server), Shelfarr (the request portal)
  # and books-setup, which wires the two to Prowlarr and SABnzbd.
  #
  # Part of `flake.nixosModules.server`: every Modules/Server/*.nix file except
  # home-assistant.nix, marsbar.nix and _lib.nix defines that same module, and the
  # definitions merge. Layout and shared pieces: see default.nix.

  flake.nixosModules.server = { config, pkgs, lib, ... }:
  let
    inherit (import ./_lib.nix { inherit pkgs; }) waitForHttp;
    inherit (config.asgard) vethHostIp;
  in
  {

# ══════════════════════════════════════════════════════════════════════════════
# BOOKS — Audiobookshelf (server) + Shelfarr (request portal)
# Audiobookshelf: port 13378 — serves ebooks + audiobooks (Jellyfin-style UI)
# Shelfarr:       port 5056  — Jellyseerr-style request portal for books
#   Connects to Prowlarr (search) + SABnzbd (download) → delivers to ABS
#
# All the wiring between the three (ABS root user + libraries + API key,
# Shelfarr's indexer / download client / ABS connection) is done by
# books-setup.service below — there is no post-boot clicking.
# ══════════════════════════════════════════════════════════════════════════════

    # Audiobookshelf — ebook + audiobook server
    virtualisation.oci-containers.containers.audiobookshelf = {
      image = "ghcr.io/advplyr/audiobookshelf:latest";
      ports = [ "13378:80" ];
      volumes = [
        "/var/lib/audiobookshelf/config:/config"
        "/var/lib/audiobookshelf/metadata:/metadata"
        "/data/media/audiobooks:/audiobooks"
        "/data/media/books:/ebooks"
      ];
      environment = {
        TZ = "Australia/Sydney";
      };
      autoStart = true;
    };

    # Shelfarr — Jellyseerr-style book request portal
    # RAILS_MASTER_KEY is auto-generated on first run and stored in /var/lib/shelfarr.
    # As long as the volume persists, the key is preserved across rebuilds.
    virtualisation.oci-containers.containers.shelfarr = {
      image = "ghcr.io/pedro-revez-silva/shelfarr:latest";
      ports = [ "5056:4000" ];
      volumes = [
        "/var/lib/shelfarr:/rails/storage"
        "/data/media/audiobooks:/audiobooks"
        "/data/media/books:/ebooks"
        "/downloads:/downloads"
      ];
      environment = {
        PUID                = "1000";
        # The real `media` gid. This was a literal "1001", copied from a
        # `users.groups.media.gid = 1001` that never took effect — nixflix
        # mkForces the group to 169 — so the container ran in a group that
        # does not exist on the host. That is also why /data/media/books and
        # audiobooks are 0777 (see the tmpfiles rules).
        PGID                = toString config.users.groups.media.gid;
        SOLID_QUEUE_IN_PUMA = "1";
        HTTP_PORT           = "4000";  # Go proxy port — must differ from Rails/Puma (3000)
      };
      autoStart = true;
    };

    # ── books-setup.service ───────────────────────────────────────────────────
    # Makes the ebook pipeline reproducible. Until 2026-09-17 this was a
    # "Post-boot (one-time)" comment telling you to click through two web UIs —
    # and it had never been done, so Audiobookshelf sat uninitialised and
    # Shelfarr had zero indexers for three months while Glance showed both
    # green. A running container is not a working pipeline.
    #
    # Idempotent, runs on every rebuild, converges a fresh install:
    #   1. Audiobookshelf — create the root user, then the two libraries
    #   2. Audiobookshelf — mint an API key for Shelfarr
    #   3. Shelfarr       — point it at Prowlarr, SABnzbd and Audiobookshelf
    #
    # ⚠️ Shelfarr's config MUST go through `bin/rails runner`, never sqlite3.
    # `AcquisitionProvider` and `DownloadClient` declare `encrypts :api_key`, so
    # a raw SQL insert stores the key in plaintext and Rails then throws on
    # decrypt. The ActiveRecord::Encryption keys live in the storage volume
    # (`.encryption_keys`), alongside `.secret_key_base` — both are generated by
    # the container's entrypoint on first run and must be sourced before
    # `bin/rails` will even boot.
    #
    # ⚠️ Prowlarr is NOT an `AcquisitionProvider`. That model is for *custom*
    # direct-download providers and its `test_connection` returns false for a
    # Prowlarr URL. Prowlarr is configured through `Setting` rows
    # (`indexer_provider` / `prowlarr_url` / `prowlarr_api_key`) instead. Getting
    # this wrong looks like a working config that silently finds nothing.
    #
    # ⚠️ `prowlarr_url` is `http://10.200.1.1:9696` — the veth host address,
    # `asgard.vethHostIp` — and is deliberately DIFFERENT from every other URL here.
    # Shelfarr builds each result's download_url from it and gives SABnzbd
    # `mode=addurl`, so SAB fetches the NZB itself. SAB lives in the Mullvad
    # network namespace and is *not* a podman container, so it cannot resolve
    # `host.containers.internal`. 10.200.1.1 is the one address reachable from
    # both the Shelfarr container and the VPN namespace (both verified 302).
    # Symptom when wrong: the item sits in SAB at 0% showing "Fetch NZB from
    # URL" with an exponentially growing WAIT, and never fails outright.
    # This also needs `veth-vpn-br` in `firewall.trustedInterfaces` (default.nix),
    # without which the namespace can ping the host but every TCP connect drops.
    #
    # ⚠️ QUOTING: the Ruby below is passed as `bin/rails runner "..."` nested
    # inside `sh -c '...'`. Inside that Ruby block you must avoid **double
    # quotes**, **backticks** and **apostrophes** — a double quote ends the
    # runner argument, a backtick becomes command substitution, and an
    # apostrophe ends the sh -c string. All three produce confusing build-time
    # or run-time syntax errors far from the real edit. Keep commentary that
    # needs punctuation out here, at Nix level, where it never reaches a shell.
    systemd.services.books-setup = {
      description = "Configure Audiobookshelf + Shelfarr (idempotent)";
      after = [ "podman-shelfarr.service" "podman-audiobookshelf.service" "podman-flaresolverr.service" ];
      wants = [ "podman-shelfarr.service" "podman-audiobookshelf.service" "podman-flaresolverr.service" ];
      wantedBy = [ "multi-user.target" ];
      # Retry a failed run, but give up after 5 tries instead of looping forever.
      # These are UNIT settings: under [Service] StartLimitBurst has no interval
      # to count against, so it never tripped. 30 min rather than the 10 its
      # siblings use, because one attempt can legitimately spend 5 min waiting
      # for Audiobookshelf — five slow attempts must still land in one window.
      unitConfig = {
        RequiresMountsFor = [ "/data/media" ];
        StartLimitIntervalSec = 1800;
        StartLimitBurst = 5;
      };
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        Restart = "on-failure";
        RestartSec = 30;
      };
      path = with pkgs; [ curl jq gnugrep gnused coreutils podman ];
      script = ''
        # Fail fast, on purpose. This was written as `set -uo pipefail` — but
        # NixOS prepends `set -e` to every unit script, so it has always been
        # fail-fast in practice, and that is the right behaviour here: every
        # step feeds the next (no token, no libraries, no API key → a Shelfarr
        # that "succeeds" with half a config), and Restart=on-failure above is
        # what turns an early exit into a retry. Spelled out so it is not an
        # accident any more.
        set -euo pipefail
        ABS=http://localhost:13378

        ${waitForHttp { name = "Audiobookshelf"; url = "$ABS/status"; tries = 60; interval = 5; }}

        U=$(cat ${config.sops.secrets."admin-username".path})
        P=$(cat ${config.sops.secrets."admin-password".path})
        # Credentials go into JSON via jq reading the environment, never spliced
        # in by hand: a quote in the password used to break the body, and on the
        # command line it was readable by anyone in /proc/<pid>/cmdline.
        export U P
        creds() { jq -n '{username: $ENV.U, password: $ENV.P}'; }

        # ── 1. root user (only if the server has never been initialised) ──
        if ! curl -sf --max-time 10 "$ABS/status" | grep -q '"isInit":true'; then
          echo "ABS: initialising root user"
          creds | jq '{newRoot: .}' \
            | curl -sf --max-time 20 -X POST "$ABS/init" -H 'Content-Type: application/json' \
                --data-binary @- >/dev/null
        fi

        # `|| true`: under set -e a failed login would abort inside the command
        # substitution, before the explicit message below could say why.
        TOK=$(creds | curl -sf --max-time 20 -X POST "$ABS/login" -H 'Content-Type: application/json' \
          --data-binary @- \
          | grep -oE '"(accessToken|token)":"[^"]+"' | head -1 | sed 's/.*:"//;s/"//') || true
        [ -n "$TOK" ] || { echo "ABS: login failed"; exit 1; }

        # ── 2. libraries, keyed by name so a re-run never duplicates them ──
        LIBS=$(curl -sf --max-time 20 -H "Authorization: Bearer $TOK" "$ABS/api/libraries")
        mklib() { # $1 = name, $2 = container path, $3 = icon
          echo "$LIBS" | grep -q "\"name\":\"$1\"" && return 0
          echo "ABS: creating library $1 -> $2"
          curl -sf --max-time 20 -X POST "$ABS/api/libraries" \
            -H "Authorization: Bearer $TOK" -H 'Content-Type: application/json' \
            -d "{\"name\":\"$1\",\"folders\":[{\"fullPath\":\"$2\"}],\"mediaType\":\"book\",\"icon\":\"$3\"}" >/dev/null
        }
        mklib Ebooks /ebooks book
        mklib Audiobooks /audiobooks audiobookshelf

        LIBS=$(curl -sf --max-time 20 -H "Authorization: Bearer $TOK" "$ABS/api/libraries")
        libid() { echo "$LIBS" | sed 's/},{/}\n{/g' | grep "\"name\":\"$1\"" \
          | grep -oE '"id":"[^"]+"' | head -1 | sed 's/.*:"//;s/"//'; }
        EBOOK_LIB=$(libid Ebooks)
        AUDIO_LIB=$(libid Audiobooks)

        # ── 3. API key for Shelfarr ──
        # The key's plaintext is only ever returned at creation, so it cannot be
        # re-read later. Only mint a new one when Shelfarr has no usable key.
        HAVE=$(podman exec shelfarr sh -c '. /rails/storage/.encryption_keys; export SECRET_KEY_BASE=$(cat /rails/storage/.secret_key_base); cd /rails && ./bin/rails runner "print Setting.find_by(key: %q(audiobookshelf_api_key))&.value.to_s.length"' 2>/dev/null || echo 0)
        if [ "''${HAVE:-0}" -lt 20 ]; then
          MYID=$(curl -sf --max-time 20 -H "Authorization: Bearer $TOK" "$ABS/api/me" \
            | grep -oE '"id":"[^"]+"' | head -1 | sed 's/.*:"//;s/"//')
          ABS_KEY=$(curl -sf --max-time 20 -X POST "$ABS/api/api-keys" \
            -H "Authorization: Bearer $TOK" -H 'Content-Type: application/json' \
            -d "{\"name\":\"shelfarr\",\"userId\":\"$MYID\",\"isActive\":true}" \
            | grep -oE '"apiKey":"[^"]+"' | head -1 | sed 's/.*:"//;s/"//')
          echo "ABS: minted a new API key for Shelfarr"
        else
          ABS_KEY=""   # keep whatever Shelfarr already holds
          echo "ABS: Shelfarr already holds an API key, leaving it alone"
        fi

        # ── 4. Shelfarr ──
        podman exec \
          -e PROWLARR_KEY="$(cat ${config.sops.secrets."prowlarr-api-key".path})" \
          -e SAB_KEY="$(cat ${config.sops.secrets."sabnzbd-api-key".path})" \
          -e ABS_KEY="$ABS_KEY" \
          -e ABS_URL="http://host.containers.internal:13378" \
          -e ABS_EBOOK_LIB="$EBOOK_LIB" \
          -e ABS_AUDIO_LIB="$AUDIO_LIB" \
          shelfarr sh -c '. /rails/storage/.encryption_keys; export SECRET_KEY_BASE=$(cat /rails/storage/.secret_key_base); cd /rails && ./bin/rails runner "
            H = %q(http://host.containers.internal)
            d = DownloadClient.find_or_initialize_by(name: %q(SABnzbd))
            d.assign_attributes(client_type: %q(sabnzbd), url: %(#{H}:8080),
              api_key: ENV.fetch(%q(SAB_KEY)), category: %q(books),
              download_path: %q(/downloads), enabled: true, priority: 0)
            changed = 0
            # api_key is encrypted non-deterministically, so re-assigning the
            # same plaintext still reports as changed. Counting it would bounce
            # the container on every single rebuild, so ignore that one field.
            changed += 1 if d.new_record? || d.changed.any? { |a| a != %q(api_key) }
            d.save!
            vals = {
              %q(indexer_provider)  => %q(prowlarr),

              # veth host address, NOT host.containers.internal. See the note
              # above the service definition - do not change without reading it.
              %q(prowlarr_url)      => %q(http://${vethHostIp}:9696),
              %q(prowlarr_api_key)  => ENV.fetch(%q(PROWLARR_KEY)),
              %q(audiobookshelf_url) => ENV.fetch(%q(ABS_URL)),
              %q(audiobookshelf_ebook_library_id)     => ENV.fetch(%q(ABS_EBOOK_LIB)),
              %q(audiobookshelf_audiobook_library_id) => ENV.fetch(%q(ABS_AUDIO_LIB)),
              # Container -> host, so NOT localhost. Shelfarr uses this for
              # Cloudflare-protected book indexers the same way Suwayomi does
              # for manga sources.
              %q(flaresolverr_url) => %(#{H}:8191),

              # Jellyseerr-style behaviour: a request should grab on its own.
              # Upstream ships this OFF, which leaves every request parked at
              # status=pending forever waiting for someone to hand-pick a
              # release in the UI — it looks like the download silently failed.
              %q(auto_select_enabled) => %q(true),

              # Upstream puts torrent FIRST (see the Nix note above). SABnzbd is
              # the only download client here, so that order makes Shelfarr
              # prefer releases it physically cannot fetch. Built via to_json so
              # no literal double quotes appear in this block.
              %q(preferred_download_types) => [%q(usenet), %q(direct)].to_json,

              # Upstream threshold is 90 and nothing reached it: the best real
              # match for a book scored 88, so every request stalled awaiting
              # manual selection. 85 clears it while still refusing junk.
              %q(auto_select_confidence_threshold) => %q(85),

              # Ships empty, which leaves format unscored. Naming the formats
              # lifted the winning result from 88 to 100, and is what makes the
              # threshold comfortable rather than marginal. epub first so the
              # Audiobookshelf reader and Moon+ both get their best case.
              %q(ebook_preferred_formats) => [%q(epub), %q(mobi), %q(azw3)].to_json
            }
            k = ENV[%q(ABS_KEY)].to_s
            vals[%q(audiobookshelf_api_key)] = k unless k.empty?
            vals.each { |key, v| s = Setting.find_or_initialize_by(key: key); s.value = v; changed += 1 if s.changed?; s.save! }
            IndexerClient.reset_all_connections!
            puts %(SETTINGS_CHANGED=#{changed})
            puts %(shelfarr: indexer=#{IndexerClient.provider} ok=#{IndexerClient.test_connection} sab=#{DownloadClient.first.adapter.test_connection})
          "' | tee /tmp/books-setup-out

        # ── 5. Restart Shelfarr if anything actually changed ───────────────────
        # Settings are read ONCE at boot and cached in the long-lived Puma and
        # SolidQueue processes. Writing the DB from a short-lived `rails runner`
        # updates the row but NOT the running app — and
        # `IndexerClient.reset_all_connections!` only resets the runner process,
        # not the workers that serve requests.
        #
        # Without this restart the service reports success, the DB looks right,
        # and the app keeps emitting the OLD value indefinitely. That is exactly
        # how a corrected `prowlarr_url` kept producing unreachable NZB URLs and
        # books kept stalling in SAB on "Fetch NZB from URL".
        #
        # Conditional so a no-op rebuild does not bounce the container.
        if grep -qE 'SETTINGS_CHANGED=[1-9]' /tmp/books-setup-out; then
          echo "books-setup: settings changed, restarting shelfarr to clear its cache"
          ${pkgs.systemd}/bin/systemctl restart podman-shelfarr

          ${waitForHttp { name = "Shelfarr"; url = "http://localhost:5056/session/new"; tries = 24; interval = 5; }}

          # Stored `SearchResult.download_url` rows keep whatever prowlarr_url
          # was in effect when that search ran. A URL change therefore strands
          # every in-flight request on a dead link — and because SAB retries a
          # bad fetch forever with a growing WAIT rather than failing, it looks
          # identical to the bug having never been fixed. Drop them and reset
          # those requests so the app re-searches and rebuilds the links.
          podman exec shelfarr sh -c '. /rails/storage/.encryption_keys; export SECRET_KEY_BASE=$(cat /rails/storage/.secret_key_base); cd /rails && ./bin/rails runner "
            good = Setting.find_by(key: %q(prowlarr_url))&.value.to_s
            stale = SearchResult.where.not(download_url: nil).reject { |s| s.download_url.start_with?(good) }
            if stale.any?
              reqs = stale.map(&:request_id).uniq
              stale.each(&:destroy)
              Request.where(id: reqs).where.not(status: %q(completed)).update_all(status: %q(pending))
              # Resetting to pending is not enough on its own — nothing re-scans
              # pending requests, so they would sit there forever looking like a
              # silent failure. Re-enqueue the search for each one.
              Request.where(id: reqs, status: %q(pending)).each { |q| SearchJob.perform_later(q.id) }
              puts %(books-setup: purged #{stale.size} stale-host search results, re-queued #{reqs.size} requests)
            end
          "' || true
        fi
        rm -f /tmp/books-setup-out
      '';
    };

  };
}
