{ self, inputs, ... }: {

  flake.nixosModules.server = { config, pkgs, lib, activeUser, ... }: {

    imports = [ inputs.nixflix.nixosModules.default ];

# ══════════════════════════════════════════════════════════════════════════════
# NIXFLIX — Arr Stack + Jellyfin + SABnzbd
# Auto-wires: Prowlarr ↔ Sonarr/Radarr/Lidarr, Seerr ↔ Jellyfin/Sonarr/Radarr
# All API keys pre-generated and stored in sops — fully reproducible on deploy.
#
# Port reference (Tailscale-only unless noted):
#   Sonarr     8989  |  Radarr    7878  |  Lidarr   8686
#   Prowlarr   9696  |  Readarr   8787  |  SABnzbd  8080
#   Jellyfin   8096  (+ Cloudflare tunnel at jellyfin.bifrost-vault.com)
#   Jellyseerr 5055  (+ Cloudflare tunnel at requests.bifrost-vault.com)
# ══════════════════════════════════════════════════════════════════════════════

    nixflix = {
      enable = true;
      mediaDir    = "/data/media";
      downloadsDir = "/data/downloads";
      stateDir    = "/data/.state/services";

      sonarr = {
        enable = true;
        config = {
          apiKey._secret = config.sops.secrets."sonarr-api-key".path;
          hostConfig.authenticationRequired = "disabled";
        };
      };

      radarr = {
        enable = true;
        config = {
          apiKey._secret = config.sops.secrets."radarr-api-key".path;
          hostConfig.authenticationRequired = "disabled";
        };
      };

      lidarr = {
        enable = true;
        config = {
          apiKey._secret = config.sops.secrets."lidarr-api-key".path;
          hostConfig.authenticationRequired = "disabled";
        };
      };

      prowlarr = {
        enable = true;
        config = {
          apiKey._secret = config.sops.secrets."prowlarr-api-key".path;
          hostConfig.authenticationRequired = "disabled";
        };
      };

      jellyfin = {
        enable = true;
        config = {
          apiKey._secret = config.sops.secrets."jellyfin-api-key".path;
          admin.password._secret = config.sops.secrets."jellyfin-admin-password".path;
        };
      };

      # Jellyseerr — media request portal (exposed via Cloudflare tunnel)
      seerr = {
        enable = true;
        config.apiKey._secret = config.sops.secrets."jellyseerr-api-key".path;
      };

      # SABnzbd usenet download client
      usenetClients.sabnzbd = {
        enable = true;
        settings.misc = {
          api_key._secret = config.sops.secrets."sabnzbd-api-key".path;
          nzb_key._secret = config.sops.secrets."sabnzbd-nzb-key".path;
          port = 8080;
        };
      };
    };

    # Readarr (book grabber) — not yet in Nixflix, use native NixOS service
    services.readarr = {
      enable = true;
      openFirewall = false;
    };
    users.users.readarr.extraGroups = [ "media" ];


# ══════════════════════════════════════════════════════════════════════════════
# BOOKS — Kavita book server
# Android: install Kavita app → connect to http://<tailscale-ip>:5000
# Post-boot: add Readarr to Prowlarr in the Prowlarr UI (Settings → Apps)
# Port: 5000 (Tailscale only)
# ══════════════════════════════════════════════════════════════════════════════

    virtualisation.oci-containers.containers.kavita = {
      image = "lscr.io/linuxserver/kavita:latest";
      ports = [ "5000:5000" ];
      volumes = [
        "/var/lib/kavita:/config"
        "/data/media/books:/books"
      ];
      environment = {
        PUID = "1000"; # rock user
        PGID = "1001"; # media group
        TZ   = "Australia/Sydney";
      };
      autoStart = true;
    };


# ══════════════════════════════════════════════════════════════════════════════
# DASHBOARD — Homarr homelab dashboard
# Note: arr API key integrations must be entered in the Homarr UI post-boot
# (Homarr stores integration credentials in its own DB, not injectable via env).
# Port: 7575 (Tailscale only)
# ══════════════════════════════════════════════════════════════════════════════

    virtualisation.oci-containers.containers.homarr = {
      image = "ghcr.io/ajnart/homarr:latest";
      ports = [ "7575:7575" ];
      volumes = [
        "/var/lib/homarr:/app/data/configs"
        "/run/podman/podman.sock:/var/run/docker.sock:ro"
      ];
      environmentFiles = [ config.sops.secrets."homarr-env".path ];
      autoStart = true;
    };


# ══════════════════════════════════════════════════════════════════════════════
# AUTOMATION — Decluttarr queue cleaner
# Polls arr service APIs to remove stalled/failed downloads automatically.
# DEFERRED until first boot (needs arr API keys generated by services).
# After first boot:
#   1. Retrieve API keys from each service (Settings → General → API Key)
#   2. Add to sops: sops ~/Dots/Secrets/secrets.yaml
#        decluttarr-env: |
#          SONARR_URL=http://localhost:8989
#          SONARR_KEY=<key>
#          RADARR_URL=http://localhost:7878
#          RADARR_KEY=<key>
#          LIDARR_URL=http://localhost:8686
#          LIDARR_KEY=<key>
#          READARR_URL=http://localhost:8787
#          READARR_KEY=<key>
#          SABNZBD_URL=http://localhost:8080
#          SABNZBD_KEY=<key>
#          REMOVE_STALLED=True
#          REMOVE_FAILED_IMPORTS=True
#          REMOVE_FAILED=True
#          REMOVE_METADATA_MISSING=True
#          REMOVE_ORPHANS=True
#   3. Un-comment container and add `sops.secrets."decluttarr-env" = {};` below
#   4. Rebuild Asgard
# ══════════════════════════════════════════════════════════════════════════════

    # virtualisation.oci-containers.containers.decluttarr = {
    #   image = "ghcr.io/manimatter/decluttarr:latest";
    #   environmentFiles = [ config.sops.secrets."decluttarr-env".path ];
    #   autoStart = true;
    # };


# ══════════════════════════════════════════════════════════════════════════════
# NETWORKING — Tailscale VPN + Cloudflare Tunnel
# Native NixOS services (not containers).
#
# Tailscale: run `sudo tailscale up` after first boot to authenticate.
#
# Cloudflare tunnel setup (one-time before first build):
#   1. dash.cloudflare.com → Zero Trust → Networks → Tunnels → Create tunnel
#   2. Name it "asgard", copy the Tunnel UUID shown on the detail page
#   3. Download/copy the credentials JSON shown during creation
#   4. sops ~/Dots/Secrets/secrets.yaml
#        cloudflare-tunnel: '<full credentials JSON>'
#   5. Replace TUNNEL-UUID-HERE below with the actual UUID
#
# Public URLs (bifrost-vault.com):
#   jellyfin.bifrost-vault.com  → localhost:8096
#   requests.bifrost-vault.com  → localhost:5055
#   photos.bifrost-vault.com    → localhost:2283
# ══════════════════════════════════════════════════════════════════════════════

    services.tailscale = {
      enable = true;
      openFirewall = true;
    };

    services.cloudflared = {
      enable = true;
      tunnels = {
        "804d54a8-e7ad-4f34-812d-3052cf862c47" = {
          credentialsFile = config.sops.secrets."cloudflare-tunnel".path;
          default = "http_status:404";
          ingress = {
            "jellyfin.bifrost-vault.com"  = "http://localhost:8096";
            "requests.bifrost-vault.com"  = "http://localhost:5055";
            "photos.bifrost-vault.com"    = "http://localhost:2283";
          };
        };
      };
    };


# ══════════════════════════════════════════════════════════════════════════════
# UTILITIES — Dozzle (container log viewer) + File Browser
# Port 8888: Dozzle    — live container logs, no auth needed (Tailscale-only)
# Port 8081: FileBrowser — full filesystem browser, set password on first login
#   Default login: admin / admin — change immediately after first boot
# Both are Tailscale-only, not exposed via Cloudflare tunnel.
# ══════════════════════════════════════════════════════════════════════════════

    virtualisation.oci-containers.containers.dozzle = {
      image = "amir20/dozzle:latest";
      ports = [ "8888:8080" ];
      volumes = [ "/run/podman/podman.sock:/var/run/docker.sock:ro" ];
      autoStart = true;
    };

    virtualisation.oci-containers.containers.filebrowser = {
      image = "filebrowser/filebrowser:latest";
      ports = [ "8081:80" ];
      volumes = [
        "/:/srv"
        "/var/lib/filebrowser/filebrowser.db:/database/filebrowser.db"
        "/var/lib/filebrowser/.filebrowser.json:/.filebrowser.json"
      ];
      autoStart = true;
    };


# ══════════════════════════════════════════════════════════════════════════════
# PHOTOS — Immich photo server
# Native NixOS module — manages its own PostgreSQL and Redis automatically.
# Public URL: photos.bifrost-vault.com (via Cloudflare tunnel)
# Port: 2283
# Post-boot: create admin account at http://localhost:2283 on first visit.
# ══════════════════════════════════════════════════════════════════════════════

    services.immich = {
      enable = true;
      mediaLocation = "/data/photos";
      openFirewall = false;
    };


# ══════════════════════════════════════════════════════════════════════════════
# INFRASTRUCTURE — Podman, media group, data directories, sops secrets
# ══════════════════════════════════════════════════════════════════════════════

    # --- Podman (OCI backend for all containers above) ---
    virtualisation.oci-containers.backend = "podman";
    virtualisation.podman = {
      enable = true;
      dockerSocket.enable = true; # compat socket for Dozzle and Homarr
    };
    # Allow containers to reach host-bound services (arr, immich, etc.)
    networking.firewall.trustedInterfaces = [ "podman0" "cni-podman0" ];

    # --- Shared media group (GID 1001) ---
    # All service users and containers use this group for /data/media access.
    users.groups.media = { gid = 1001; };
    users.users.${activeUser}.extraGroups = [ "media" ];
    users.users.jellyfin.extraGroups = [ "media" ];

    # --- Data directories ---
    systemd.tmpfiles.rules = [
      "d /data                      0755 root  root  -"
      "d /data/media                0775 root  media -"
      "d /data/media/tv             0775 root  media -"
      "d /data/media/movies         0775 root  media -"
      "d /data/media/music          0775 root  media -"
      "d /data/media/books          0775 root  media -"
      "d /data/downloads            0775 root  media -"
      "d /data/downloads/usenet     0775 root  media -"
      "d /data/photos               0775 root  media -"
      "d /data/.state/services      0775 root  media -"
      # Container state dirs
      "d /var/lib/kavita            0775 root  media -"
      "d /var/lib/homarr            0775 root  media -"
      "d /var/lib/filebrowser       0775 root  media -"
    ];

    # --- Sops secrets ---
    # All secrets live in Secrets/secrets.yaml.
    # Before first build, populate them with:
    #
    #   sops ~/Dots/Secrets/secrets.yaml
    #
    # Add each key as a plain string (generate with: openssl rand -hex 16):
    #   sonarr-api-key: "<32 hex chars>"
    #   radarr-api-key: "<32 hex chars>"
    #   lidarr-api-key: "<32 hex chars>"
    #   prowlarr-api-key: "<32 hex chars>"
    #   seerr-api-key: "<32 hex chars>"
    #   sabnzbd-api-key: "<32 hex chars>"
    #   sabnzbd-nzb-key: "<32 hex chars>"
    #   jellyfin-api-key: "<32 hex chars>"
    #   jellyfin-admin-password: "<your chosen password>"
    #   cloudflare-tunnel: "<full credentials JSON from Cloudflare dashboard>"
    #   homarr-env: |
    #     SECRET_ENCRYPTION_KEY=<32 chars — openssl rand -hex 16>
    sops.secrets."sonarr-api-key"           = {};
    sops.secrets."radarr-api-key"           = {};
    sops.secrets."lidarr-api-key"           = {};
    sops.secrets."prowlarr-api-key"         = {};
    sops.secrets."jellyseerr-api-key"        = {};
    sops.secrets."sabnzbd-api-key"          = {};
    sops.secrets."sabnzbd-nzb-key"          = {};
    sops.secrets."jellyfin-api-key"         = {};
    sops.secrets."jellyfin-admin-password"  = {};
    sops.secrets."cloudflare-tunnel"        = {};
    sops.secrets."homarr-env"               = {};

    # Kernel UDP buffer tuning for smooth streaming over Tailscale
    boot.kernel.sysctl = {
      "net.core.rmem_max"           = 26214400;
      "net.core.wmem_max"           = 26214400;
      "net.core.netdev_max_backlog" = 5000;
    };

  };
}
