{ ... }:
let
  # ── Wallpaper colours for Discord ───────────────────────────────────────────
  # Rendered by skwd into ~/.config/vesktop/themes/matugen.theme.css and enabled
  # as a Vencord theme. Deliberately a COLOURS-ONLY file: nothing but custom
  # properties on :root, no selectors and no layout.
  #
  # That constraint is the whole point. noctalia ships a community `discord`
  # template, and it was enabled here briefly on 2026-09-15 — but it is a 20 KB
  # full redesign (opaque panels, gaps, borders, restyled top bar) and this host
  # runs Vesktop with `transparent = true` plus a quickCss that forces everything
  # transparent with !important. Loading both at once made Discord visibly
  # glitch. A variables-only file cannot conflict with quickCss, because
  # quickCss is what consumes it.
  #
  # Cannot render into quickCss.css itself: that is an xdg.configFile, i.e. a
  # read-only store symlink. Hence a second file that quickCss references.
  discordMatugenTemplate = ''
    /* Generated by skwd on every wallpaper change — do not edit.
       Consumed by quickCss.css (Modules/Apps/discord.nix). Colours only. */
    :root {
      --skwd-accent: {{colors.primary.default.hex}};
      --skwd-accent-rgb: {{colors.primary.default.red}}, {{colors.primary.default.green}}, {{colors.primary.default.blue}};
      --skwd-on-accent: {{colors.on_primary.default.hex}};

      --skwd-surface-rgb: {{colors.surface.default.red}}, {{colors.surface.default.green}}, {{colors.surface.default.blue}};
      --skwd-surface-variant-rgb: {{colors.surface_variant.default.red}}, {{colors.surface_variant.default.green}}, {{colors.surface_variant.default.blue}};
      --skwd-container-rgb: {{colors.surface_container.default.red}}, {{colors.surface_container.default.green}}, {{colors.surface_container.default.blue}};

      --skwd-text: {{colors.on_surface.default.hex}};
      --skwd-text-rgb: {{colors.on_surface.default.red}}, {{colors.on_surface.default.green}}, {{colors.on_surface.default.blue}};
      --skwd-subtext: {{colors.on_surface_variant.default.hex}};
      --skwd-outline: {{colors.outline.default.hex}};
      --skwd-error: {{colors.error.default.hex}};
    }
  '';

  # Name of the Vencord theme file skwd renders into. Vencord enables themes by
  # bare filename within ~/.config/vesktop/themes/.
  matugenThemeFile = "matugen.theme.css";
in {
  # Consumed by Modules/Desktop/skwd.nix, which installs this into skwd's matugen
  # template dir and registers the "discord" integration. Same split as
  # flake.lib.btop / flake.lib.steam: the mapping has exactly one definition.
  flake.lib.discord = {
    inherit matugenThemeFile;
    matugenTemplate = discordMatugenTemplate;
  };

  flake.nixosModules.discord = { pkgs, activeUser, ... }: let
    # Vesktop does NOT read ~/.config/vesktop/argv.json — the string appears nowhere
    # in its app.asar. Chromium switches must reach Electron on the real command line.
    # The nixpkgs vesktop wrapper ends in `exec electron app.asar … "$@"`, so flags
    # added here are forwarded through.
    #
    # WebRtcAllowInputVolumeAdjustment: Chromium's AGC does not merely apply gain in
    # software — on Linux its analog stage rewrites the *hardware* source volume via
    # the Pulse API, which PipeWire honours. That produces a monotonic downward ratchet
    # (measured 1.00 → 0.94 → 0.88 → 0.82 → 0.76 → 0.71 over ~90s) which never recovers,
    # and because it moves the device volume rather than a stream volume it degrades the
    # mic for every other app and persists after Discord exits. CLI equivalent of
    # chrome://flags#enable-webrtc-allow-input-volume-adjustment → Disabled.
    # Pair with Discord → Settings → Voice & Video → Automatic Gain Control: off, which
    # is stored server-side per-account and cannot be set declaratively.
    #
    # Only --disable-features is safe to add here. Vesktop itself calls
    # appendSwitch("enable-features", …) and the nixpkgs wrapper passes
    # --enable-features=WaylandWindowDecorations under NIXOS_OZONE_WL; duplicate
    # --enable-features on one command line means last-wins, so adding another would
    # silently drop Wayland decorations. Verify after changing:
    #   tr '\0' '\n' < /proc/$(pgrep -f vesktop | head -1)/cmdline | grep features
    vesktopAgcOff = pkgs.symlinkJoin {
      name = "vesktop-agc-off";
      paths = [ pkgs.vesktop ];
      nativeBuildInputs = [ pkgs.makeWrapper ];
      postBuild = ''
        wrapProgram $out/bin/vesktop \
          --add-flags "--disable-features=WebRtcAllowInputVolumeAdjustment"
      '';
    };
  in {
    home-manager.users.${activeUser} = { lib, ... }: {
      home.packages = [ vesktopAgcOff ];

      # Desktop entry that shows as "Discord" instead of "Vesktop"
      xdg.desktopEntries.discord = {
        name = "Discord";
        exec = "vesktop %U";
        icon = "discord";
        comment = "Discord with Vencord";
        categories = [ "Network" "InstantMessaging" ];
        terminal = false;
      };

      # Clear Vesktop's Chromium caches when — and only when — Vesktop itself
      # changes. Added (with no more detail than "prevent EPIPE errors") as an
      # unconditional wipe on EVERY switch, which cost a slow, cache-cold next
      # launch each time and deleted files out from under a running Vesktop.
      #
      # What it guards against is Electron's: Cache / Code Cache / GPUCache are
      # written by one Electron+Chromium build and are not guaranteed readable
      # by the next, so stale caches after an upgrade are a classic source of
      # crashes and broken IPC. The vesktop store path changes whenever Vesktop
      # OR the Electron it is built on changes, so it is exactly the right key.
      # The stamp records the build the caches were last cleared for; delete it
      # to force a clear on the next switch.
      home.activation.clearVesktopCache = lib.hm.dag.entryAfter [ "writeBoundary" ] (
        let
          stamp = "$HOME/.config/vesktop/.dots-vesktop-build";
          build = pkgs.writeText "vesktop-build" "${pkgs.vesktop}";
        in ''
          if [ "$(cat "${stamp}" 2>/dev/null)" != "${pkgs.vesktop}" ]; then
            run rm -rf "$HOME/.config/vesktop/Cache" \
                       "$HOME/.config/vesktop/Code Cache" \
                       "$HOME/.config/vesktop/GPUCache"
            run mkdir -p "$HOME/.config/vesktop"
            run install -m 0644 ${build} "${stamp}"
          fi
        ''
      );

      # Vencord settings with transparent theme
      #
      # Structure and opacity only — the COLOURS come from
      # ~/.config/vesktop/themes/${matugenThemeFile}, which skwd re-renders on
      # every wallpaper change (see flake.lib.discord above). Every var has a
      # fallback to the old flat black, so Discord degrades to exactly its former
      # appearance if that file is missing (fresh install, skwd not running yet,
      # theme disabled) rather than rendering untinted or transparent.
      xdg.configFile."vesktop/settings/quickCss.css".text = ''
        /* Transparent Discord for compositor transparency */
        :root {
          --background-primary: transparent !important;
          --background-secondary: rgba(var(--skwd-surface-rgb, 0, 0, 0), 0.4) !important;
          --background-secondary-alt: rgba(var(--skwd-surface-rgb, 0, 0, 0), 0.3) !important;
          --background-tertiary: rgba(var(--skwd-surface-variant-rgb, 0, 0, 0), 0.5) !important;
          --background-floating: rgba(var(--skwd-container-rgb, 0, 0, 0), 0.7) !important;
          --background-modifier-hover: rgba(var(--skwd-text-rgb, 255, 255, 255), 0.05) !important;
          --background-modifier-selected: rgba(var(--skwd-text-rgb, 255, 255, 255), 0.1) !important;
        }

        .theme-dark {
          --background-primary: transparent !important;
          --background-secondary: rgba(var(--skwd-surface-rgb, 0, 0, 0), 0.4) !important;
          --background-secondary-alt: rgba(var(--skwd-surface-rgb, 0, 0, 0), 0.3) !important;
          --background-tertiary: rgba(var(--skwd-surface-variant-rgb, 0, 0, 0), 0.5) !important;
        }

        /* Main app background */
        .app-3xd6d0,
        .app-2CXKsg,
        .appMount-2yBXZl,
        .bg-1QIAus,
        .container-1eFtFS,
        .chat-2ZfjoI,
        .chatContent-3KubbW,
        .members-3WRCEx,
        .membersWrap-3NUR2t {
          background: transparent !important;
        }

        /* Sidebar */
        .sidebar-1tnWFu,
        .container-1NXEtd,
        .panels-3wFtMD {
          background: transparent !important;
        }

        /* Server list */
        .wrapper-1_HaEi,
        .scroller-3X7KbA {
          background: transparent !important;
        }

        /* Channel list */
        .container-1NXEtd,
        .nav-2gJm_S {
          background: transparent !important;
        }
      '';

      # NOTE: there was a `vesktop/argv.json` here carrying
      # --enable-features=WebRTCPipeWireCapturer. Vesktop never read it (verified: the
      # string "argv.json" does not occur in app.asar), so that flag was never applied
      # despite being documented as the dropout fix. Removed rather than left as a
      # no-op. Chromium switches now go through the wrapper at the top of this file.

      # Vesktop's own (Electron/window) settings. NOT Vencord's.
      #
      # `enabledThemes = [ "quickCss.css" ]` used to live here and was a no-op on
      # two counts — same class of bug as the argv.json one noted above, so it is
      # called out rather than quietly dropped:
      #   1. Vencord reads themes from vesktop/settings/settings.json, not from
      #      this file. This one only carries window-level keys (transparent,
      #      frameless, arRPC, …).
      #   2. quickCss.css is not a theme at all — it is the Quick CSS box, gated
      #      by `useQuickCss`. Listing it as a theme could never have done
      #      anything.
      # Theme enablement now happens in the activation script below.
      xdg.configFile."vesktop/settings.json".text = builtins.toJSON {
        transparent = true;
        enableReactDevtools = false;
        frameless = false;
        arRPC = true;
        disableMinSize = false;
        staticTitle = false;
        checkUpdates = false;
      };

      # ── Vencord settings: enable the matugen theme + Quick CSS ──────────────
      # Cannot be an xdg.configFile: Vencord rewrites this file at runtime for
      # every plugin toggle and setting change, so a read-only store symlink
      # would break the client. Patch just the keys Nix owns instead, the same
      # jq-upsert pattern Modules/Desktop/skwd.nix uses for skwd's config.json.
      #
      # matugen.theme.css is colours-only, so it composes with quickCss rather
      # than fighting it. Any OTHER theme left in this list is removed on
      # purpose: noctalia's community `discord` template was enabled here on
      # 2026-09-15 and its opaque full redesign made the transparent client
      # glitch badly. Leaving the list untouched would let that recur silently.
      #
      # ⚠️ A REBUILD WHILE DISCORD IS RUNNING CAN LOSE THIS. Vencord holds its
      # settings in memory and writes the whole file back on any settings change,
      # so a write that happens after activation clobbers the patch (observed
      # 2026-09-15: enabledThemes came back as [] and Discord silently fell back
      # to the quickCss fallbacks — transparent, but flat black instead of
      # wallpaper-tinted). It is self-correcting once Vencord has the value in
      # memory. If Discord looks untinted after a rebuild, reload it with Ctrl+R
      # and check this file rather than assuming the render pipeline broke.
      #
      # Home Manager's `run` cannot wrap a redirect (in a dry run it would echo
      # the command INTO the file), so the write is DRY_RUN-guarded by hand —
      # the same idiom HM's own modules use.
      home.activation.vesktopVencordSettings = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
        VC="$HOME/.config/vesktop/settings/settings.json"
        run mkdir -p "$(dirname "$VC")"

        if [[ -v DRY_RUN ]]; then
          echo "would patch $VC: useQuickCss, enabledThemes = [${matugenThemeFile}]"
        else
          [ -f "$VC" ] || echo '{}' > "$VC"

          ${pkgs.jq}/bin/jq \
            --arg theme ${builtins.toJSON matugenThemeFile} \
            '.useQuickCss = true | .enabledThemes = [$theme]' \
            "$VC" > "$VC.tmp" && mv "$VC.tmp" "$VC"
        fi
      '';
    };
  };
}
