#!/usr/bin/env python3
"""hud.py — the Asgard dashboard's HUD, generated.

    hud.py OUTDIR [VERSION]

Writes the pieces asgard.css draws the dashboard's tech-HUD look with:

    frame.svg    the panel frame round every card: a chamfered neon outline
                 (top-left and bottom-right corners cut), a soft glow, bright
                 corner brackets, and small readout marks in the corners. A
                 9-slice border-image (FC-px corners, straight edges that
                 STRETCH — nothing on an edge, so any card size is exact)
    grid.svg     the page's ground: a faint grid with circuit traces, one
                 seamless tile that REPEATS down the page — however long a
                 page is, the backdrop never runs out (a single big image did)
    forest.svg   misty pine ridges, three layers in teal fog; pinned to the
                 bottom of the screen (a fixed layer, not a fixed background,
                 so phones honour it too), tiles left-right
    ygg.svg      Yggdrasil in line art — a branching circuit tree, roots
                 below, nodes at its tips — inside a ticked HUD ring
    logo.svg     Yggdrasil as an emblem — branches, roots, lit tips — in a
                 ring: the header logo and tab icon
    hud.css      the URLs (with VERSION, so Glance's 2 h asset cache never
                 serves an old piece) and the icon set, as custom properties:
                 --h-frame --h-grid --h-forest --h-ygg, --ic-<name>
    tpl.js       the three pieces that carry the HUD's colour (the frame,
                 Yggdrasil, the logo) again, as TEMPLATES — the colours left
                 as __A__ (the HUD), __H__ (its bright), __B__ (its second
                 light), __D__ (the logo's dark fill) — for theme.js to redraw
                 in whatever colour the viewer picks

Every random choice is seeded, so every build draws the same HUD. Colours:
the HUD's own pieces in mint #3be8a8 / teal #1fc8c4 (the default — the
picker recolours them); the ground and the pines in neutral tech grey.
"""
import json
import math
import os
import random
import sys

TAU = 2 * math.pi
MINT, MINT_HOT, TEAL = "#3be8a8", "#8dffd6", "#1fc8c4"
LOGO_DARK = "#14181c"
GREY = "#aab4bd"   # the grid's lines: neutral, whatever the HUD's colour
PREC = [1]


def f(v):
    if PREC[0] == 0:
        s = "%d" % round(v)
    else:
        s = "%.1f" % v
        if s.endswith(".0"):
            s = s[:-2]
    return "0" if s == "-0" else s


def rnd(v):
    return round(v, PREC[0])


def nums(vals):
    out = ""
    for v in vals:
        t = f(v)
        out += t if (not out or t[0] == "-") else " " + t
    return out


def poly_d(pts, close=True):
    """A polyline in relative coordinates, each step from the ROUNDED previous
    point, so rounding never drifts."""
    cx, cy = rnd(pts[0][0]), rnd(pts[0][1])
    d = "M" + nums((cx, cy)) + "l"
    vals = []
    for x, y in pts[1:]:
        nx, ny = rnd(x), rnd(y)
        if nx == cx and ny == cy:
            continue
        vals += [nx - cx, ny - cy]
        cx, cy = nx, ny
    return d + nums(vals) + ("z" if close else "")


def doc(w, h, note, body, defs="", par=""):
    return ('<svg xmlns="http://www.w3.org/2000/svg" width="%d" height="%d" viewBox="0 0 %d %d"%s><!-- %s Generated by hud.py — '
            'see its header. --><defs>%s</defs>%s</svg>') % (w, h, w, h, par, note, defs, body)


GLOW = '<filter id="glow" x="-20%" y="-20%" width="140%" height="140%"><feGaussianBlur stdDeviation="SD"/></filter>'


# ── the panel frame ───────────────────────────────────────────────────────────
FC = 56          # corner slice
FK = 14          # chamfer at top-left and bottom-right


def frame():
    S, o, K = 2 * FC + 64, 1.5, FK
    outline = "M%s %sH%sV%sL%s %sH%sV%sZ" % (f(o + K), f(o), f(S - o), f(S - o - K), f(S - o - K), f(S - o), f(o), f(o + K))
    brackets = ("M%s %sV%sL%s %sH%s" % (f(o), f(o + K + 18), f(o + K), f(o + K), f(o), f(o + K + 18)) +
                "M%s %sH%sV%s" % (f(S - o - 22), f(o), f(S - o), f(o + 22)) +
                "M%s %sV%sL%s %sH%s" % (f(S - o), f(S - o - K - 18), f(S - o - K), f(S - o - K), f(S - o), f(S - o - K - 18)) +
                "M%s %sH%sV%s" % (f(o + 22), f(S - o), f(o), f(S - o - 22)))
    # readouts: three bars after the top-left bracket, ticks down the top-right,
    # a second chamfer line inside the bottom-right, a notch at the bottom-left
    marks = "".join('<rect x="%s" y="%s" width="4" height="2"/>' % (f(o + K + 24 + i * 6), f(o + 3.5)) for i in range(3))
    ticks = "".join("M%s %sh4" % (f(S - o - 7), f(o + 28 + i * 5)) for i in range(4))
    inner = "M%s %sL%s %s" % (f(S - o - 5), f(S - o - K - 6), f(S - o - K - 6), f(S - o - 5))
    notch = "M%s %sl6 0l-6 -6z" % (f(o + 3), f(S - o - 3))
    # Two-tone: the outline runs from the HUD's light (top-left) into its
    # second light (bottom-right), and each corner's bracket wears its own end
    # — so a theme's PAIR shows on every card, not just its first colour. The
    # gradient is in the source tile, so the 9-slice keeps the ends in their
    # corners and stretches the blend along the edges between them.
    tl, tr, br, bl = ("M" + p for p in brackets.split("M") if p)
    tr_bl = tr + bl
    defs = (GLOW.replace("SD", "2.2") +
            '<linearGradient id="fg" x1="0" y1="0" x2="1" y2="1"><stop offset=".18" stop-color="%s"/>'
            '<stop offset=".82" stop-color="%s"/></linearGradient>' % (MINT, TEAL))
    body = ('<path d="%s" fill="none" stroke="url(#fg)" stroke-width="5" opacity=".24" filter="url(#glow)"/>'
            '<path d="%s" fill="none" stroke="url(#fg)" stroke-width="1.1" opacity=".65"/>'
            '<path d="%s" fill="none" stroke="%s" stroke-width="5" opacity=".35" filter="url(#glow)"/>'
            '<path d="%s" fill="none" stroke="%s" stroke-width="5" opacity=".35" filter="url(#glow)"/>'
            '<path d="%s" fill="none" stroke="url(#fg)" stroke-width="5" opacity=".3" filter="url(#glow)"/>'
            '<path d="%s" fill="none" stroke="%s" stroke-width="2.2" stroke-linecap="square"/>'
            '<path d="%s" fill="none" stroke="%s" stroke-width="2.2" stroke-linecap="square"/>'
            '<path d="%s" fill="none" stroke="url(#fg)" stroke-width="2.2" stroke-linecap="square"/>'
            '<g fill="%s" opacity=".85">%s</g>'
            '<path d="%s" stroke="%s" stroke-width="1" opacity=".7"/>'
            '<path d="%s" stroke="%s" stroke-width="1" opacity=".6"/>'
            '<path d="%s" fill="%s" opacity=".7"/>') % (
        outline, outline, tl, MINT, br, TEAL, tr_bl, tl, MINT_HOT, br, TEAL, tr_bl,
        MINT, marks, ticks, MINT, inner, TEAL, notch, TEAL)
    return doc(S, S, "The panel frame round every card: a 9-slice border image (%dpx corners, stretched edges)." % FC,
               body, defs)


# ── the page's ground: grid + circuit traces, one seamless tile ───────────────
def grid(rng):
    T = 480
    body = ['<path d="%s" stroke="%s" stroke-width="1" opacity=".05" fill="none"/>' % (
        "".join("M%d 0V%d" % (x, T) for x in range(0, T, 40)) + "".join("M0 %dH%d" % (y, T) for y in range(0, T, 40)), GREY)]
    plus = "".join("M%d %dh6M%d %dv6" % (x - 3, y, x, y - 3) for x in range(40, T, 80) for y in range(40, T, 80) if rng.random() < 0.6)
    body.append('<path d="%s" stroke="%s" stroke-width="1" opacity=".1"/>' % (plus, GREY))
    # circuit traces: walked on the grid's 8px lattice, right angles and 45s,
    # kept clear of the tile's edge so the tile joins seamlessly
    traces, pads = "", ""
    for _ in range(9):
        x, y = rng.randrange(3, T // 8 - 3) * 8, rng.randrange(3, T // 8 - 3) * 8
        pts = [(x, y)]
        d = rng.choice([(1, 0), (0, 1), (-1, 0), (0, -1)])
        for _ in range(rng.randint(3, 6)):
            n = rng.randint(2, 6)
            x, y = x + d[0] * 8 * n, y + d[1] * 8 * n
            x, y = max(16, min(T - 16, x)), max(16, min(T - 16, y))
            pts.append((x, y))
            d = rng.choice([(d[1], d[0]), (-d[1], -d[0]), (d[0] or 1, d[1] or 1)])
            d = (max(-1, min(1, d[0])), max(-1, min(1, d[1])))
        traces += "M" + "L".join("%d %d" % p for p in pts)
        for px, py in (pts[0], pts[-1]):
            pads += '<circle cx="%d" cy="%d" r="2.2"/>' % (px, py)
    body.append('<path d="%s" stroke="%s" stroke-width="1" opacity=".06" fill="none"/>' % (traces, GREY))
    body.append('<g fill="none" stroke="%s" stroke-width="1" opacity=".1">%s</g>' % (GREY, pads))
    return doc(T, T, "The page's ground: grid and circuit traces, one seamless tile.", "".join(body))


# ── misty pines along the foot of the screen ─────────────────────────────────
TW, TH = 1600, 420


def spruce(x, base, h, w, rng, tier=7.0):
    top = base - h
    tiers = max(6, int(h / tier))
    R, L = [], []
    for sd, out in ((1, R), (-1, L)):
        for i in range(tiers):
            t = (i + 0.6) / tiers
            y = top + h * 0.05 + t * h * 0.88
            half = w * (0.05 + 0.95 * t ** 0.92) * rng.uniform(0.62, 1.08)
            droop = h * 0.01 + half * 0.2
            out.append((x + sd * half * rng.uniform(0.18, 0.42), y - droop * 0.2))
            out.append((x + sd * half * rng.uniform(0.62, 0.8), y + droop * 0.35))
            out.append((x + sd * half, y + droop))
            out.append((x + sd * half * rng.uniform(0.74, 0.9), y + droop * 0.8))
    return poly_d([(x, top - h * 0.04)] + R + [(x + w * 0.06, base), (x - w * 0.06, base)] + L[::-1])


def forest(rng):
    PREC[0] = 0
    try:
        out = []
        layers = [(40, (110, 180), "#3a4148", ".5", 11), (26, (170, 270), "#262b31", ".8", 8), (14, (260, 380), "#15181c", "1", 7)]
        for li, (n, (h0, h1), col, op, tier) in enumerate(layers):
            items = []
            for i in range(n):
                x = (i + rng.uniform(-0.4, 0.4)) * TW / n
                h = rng.uniform(h0, h1)
                d = spruce(x, TH + 4, h, h * 0.3, rng, tier)
                items.append(d)
                if x < 120:
                    items.append(spruce(x + TW, TH + 4, h, h * 0.3, random.Random(int(x * 13)), tier))
                if x > TW - 120:
                    items.append(spruce(x - TW, TH + 4, h, h * 0.3, random.Random(int(x * 13)), tier))
            out.append('<path d="%s" fill="%s" opacity="%s"/>' % ("".join(items), col, op))
            if li < 2:
                out.append('<rect y="%d" width="%d" height="180" fill="url(#mist)"/>' % (TH - 230 + li * 70, TW))
        defs = ('<linearGradient id="mist" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="%s" stop-opacity="0"/>'
                '<stop offset=".55" stop-color="%s" stop-opacity=".09"/><stop offset="1" stop-color="%s" stop-opacity="0"/></linearGradient>') % (GREY, GREY, GREY)
        return doc(TW, TH, "Misty pines along the foot of the screen; tiles left-right.", "".join(out), defs,
                   ' preserveAspectRatio="xMidYMax slice"')
    finally:
        PREC[0] = 1


# ── Yggdrasil, in line art ────────────────────────────────────────────────────
# The Elder Futhark, in its order, each rune as strokes in a 6×12 box centred
# on 0,0 (y down) — the band round Yggdrasil's ring.
FUTHARK = [
    "M-2 6V-6M-2 -1L3 -5M-2 3L3 -1",            # ᚠ fehu
    "M-3 6V-6L3 -2V6",                          # ᚢ uruz
    "M-2 6V-6M-2 -3L2 0L-2 3",                  # ᚦ thurisaz
    "M-2 6V-6M-2 -6L3 -3M-2 -2L3 1",            # ᚨ ansuz
    "M-2 6V-6L2 -3L-2 0L2 6",                   # ᚱ raidho
    "M2 -5L-2 0L2 5",                           # ᚲ kenaz
    "M-3 -5L3 5M3 -5L-3 5",                     # ᚷ gebo
    "M-2 6V-6L2 -3L-2 0",                       # ᚹ wunjo
    "M-2 6V-6M2 6V-6M-2 -1L2 2",                # ᚺ hagalaz
    "M0 6V-6M-2 -2L2 2",                        # ᚾ naudiz
    "M0 6V-6",                                  # ᛁ isa
    "M-1 -5L-3 -2L-1 1M1 -1L3 2L1 5",           # ᛃ jera
    "M0 6V-6M0 -6L2 -4M0 6L-2 4",               # ᛇ eihwaz
    "M-2 6V-6M-2 -6L1 -4L3 -6M-2 6L1 4L3 6",    # ᛈ perthro
    "M0 6V-6M0 -1L-3 -5M0 -1L3 -5",             # ᛉ algiz
    "M2 -6L-2 -2L2 2L-2 6",                     # ᛊ sowilo
    "M0 6V-6M-3 -3L0 -6L3 -3",                  # ᛏ tiwaz
    "M-2 6V-6L2 -3L-2 0L2 3L-2 6",              # ᛒ berkano
    "M-3 6V-6L0 -3L3 -6V6",                     # ᛖ ehwaz
    "M-3 6V-6L3 0M3 6V-6L-3 0",                 # ᛗ mannaz
    "M-2 6V-6L2 -3",                            # ᛚ laguz
    "M0 -6L3 0L0 6L-3 0Z",                      # ᛜ ingwaz
    "M-3 -5L3 5V-5L-3 5Z",                      # ᛞ dagaz
    "M-3 6L2 0L0 -5L-2 0L3 6",                  # ᛟ othala
]


def ygg(rng):
    """Yggdrasil, the world tree, for the tailnet card.

    A trunk of six strands twisting round each other, fanning at the top into
    a dome of forking, arching branches (a lit node at every tip, motes of
    light among them, an aura behind the crown) and at the foot into three
    great roots, each through one of the three wells. The NINE REALMS sit on
    it as hexagon nodes — Asgard at the crown, Midgard on the trunk, Hel
    below the roots — joined like a network. Round it: the HUD ring, its
    ticks, and a band of the 24 runes of the Elder Futhark. Branches in the
    HUD's colour, roots, wells and runes in its second light."""
    W = H = 400
    cx, cy = 200, 200
    out, glow = [], []

    # ── the ring ──
    ring = []
    ring.append('<circle cx="200" cy="200" r="191" fill="none" stroke="%s" stroke-width="1" opacity=".35"/>' % MINT)
    arcs = ""
    for k in range(4):
        a0, a1 = TAU * (k / 4 + 0.035), TAU * (k / 4 + 0.215)
        arcs += "M%s %sA195 195 0 0 1 %s %s" % (f(cx + 195 * math.cos(a0)), f(cy + 195 * math.sin(a0)), f(cx + 195 * math.cos(a1)), f(cy + 195 * math.sin(a1)))
    ring.append('<path d="%s" fill="none" stroke="%s" stroke-width="2.6" stroke-linecap="square" opacity=".9"/>' % (arcs, MINT))
    ring.append('<circle cx="200" cy="200" r="185" fill="none" stroke="%s" stroke-width="1" opacity=".55"/>' % TEAL)
    ring.append('<circle cx="200" cy="200" r="168" fill="none" stroke="%s" stroke-width="1" opacity=".55"/>' % TEAL)
    runes = ""
    for i, r in enumerate(FUTHARK):
        a = -90 + i * 15 + 7.5
        x, y = cx + 176.5 * math.cos(math.radians(a)), cy + 176.5 * math.sin(math.radians(a))
        runes += '<path transform="translate(%s %s) rotate(%s) scale(.82)" d="%s"/>' % (f(x), f(y), f(a + 90), r)
    ring.append('<g fill="none" stroke="%s" stroke-width="1.35" stroke-linecap="round" stroke-linejoin="round" opacity=".85">%s</g>' % (TEAL, runes))
    for i in range(24):                      # a dot between each pair of runes
        a = math.radians(-90 + i * 15)
        ring.append('<circle cx="%s" cy="%s" r="1.1" fill="%s" opacity=".7"/>' % (f(cx + 176.5 * math.cos(a)), f(cy + 176.5 * math.sin(a)), TEAL))
    ticks = ""
    for i in range(120):
        a = TAU * i / 120
        l = 8 if i % 10 == 0 else 3.5
        ticks += "M%s %sL%s %s" % (f(cx + 163 * math.cos(a)), f(cy + 163 * math.sin(a)), f(cx + (163 - l) * math.cos(a)), f(cy + (163 - l) * math.sin(a)))
    ring.append('<path d="%s" stroke="%s" stroke-width="1.1" opacity=".5"/>' % (ticks, MINT))
    out += ring

    # the aura behind the crown, and the horizon the tree stands on (Midgard's)
    out.append('<ellipse cx="200" cy="160" rx="145" ry="130" fill="url(#aura)"/>')
    out.append('<path d="M92 271H308" stroke="url(#horizon)" stroke-width="1.4"/>')

    # ── the tree ──
    lines = {}   # depth → path data

    def seg(depth, d):
        lines[depth] = lines.get(depth, "") + d

    def curve(x, y, a, L, bend):
        ex, ey = x + L * math.cos(a), y + L * math.sin(a)
        nx, ny = -math.sin(a), math.cos(a)
        mx, my = (x + ex) / 2 + nx * bend * L, (y + ey) / 2 + ny * bend * L
        return ex, ey, "M%s %sQ%s %s %s %s" % (f(x), f(y), f(mx), f(my), f(ex), f(ey))

    tips, joints, rtips, motes = [], [], [], []
    CX, CY, RX, RY = 200, 168, 128, 116          # the crown: a dome, wider than tall

    def inside(x, y):
        return ((x - CX) / RX) ** 2 + ((y - CY) / RY) ** 2 <= 1

    # Branches and roots grow in MIRRORED PAIRS — each pair from one seed, the
    # right-hand one reflected — so the tree stands balanced, like the emblem
    # it is, with a little jitter of its own so it isn't a perfect mirror.
    def turn(a, m):
        return a if m > 0 else math.pi - a

    def branch(r, x, y, a, L, depth, spread, m):
        lo, hi = -math.pi + 0.05, 0.12                       # never droops far below level
        a = max(lo, min(hi, a))                               # (angles are the left half's; turn() mirrors)
        ang = turn(a, m) + rng.uniform(-0.03, 0.03)
        ex, ey = x + L * math.cos(ang), y + L * math.sin(ang)
        tries = 0
        while not inside(ex, ey) and tries < 6:              # shorten to stay in the dome
            L *= 0.8
            ex, ey = x + L * math.cos(ang), y + L * math.sin(ang)
            tries += 1
        if not inside(ex, ey):
            tips.append((x, y))
            return
        ex, ey, d = curve(x, y, ang, L, r.uniform(-0.2, 0.2) * m)
        seg(depth, d)
        if depth == 0:
            tips.append((ex, ey))
            return
        if depth <= 3:
            joints.append((ex, ey))
        if depth <= 3 and r.random() < 0.55:                   # a side twig: lights INSIDE the canopy, not just round its rim
            side = 1 if r.random() < 0.5 else -1
            ta = turn(max(lo, min(hi, a + side * r.uniform(0.7, 1.1))), m)
            tx, ty, td = curve(ex, ey, ta, L * r.uniform(0.3, 0.5), r.uniform(-0.2, 0.2))
            if inside(tx, ty):
                seg(0, td)
                tips.append((tx, ty))
        if depth <= 2 and r.random() < 0.12:                   # and some branches simply end early
            tips.append((ex, ey))
            return
        kids = 3 if depth >= 3 and r.random() < 0.3 else 2
        for k in range(kids):
            off = (k - (kids - 1) / 2) * spread + r.uniform(-0.1, 0.1)
            branch(r, ex, ey, a + off, L * r.uniform(0.72, 0.82), depth - 1, spread * 0.92, m)

    def root(r, x, y, a, L, depth, spread, m):
        a = max(0.15, min(math.pi - 0.15, a))
        ang = turn(a, m) + rng.uniform(-0.03, 0.03)
        ex, ey, d = curve(x, y, ang, L, r.uniform(-0.25, 0.25) * m)
        if math.hypot(ex - cx, ey - cy) > 152:
            return
        lines["r%d" % depth] = lines.get("r%d" % depth, "") + d
        if depth == 0:
            rtips.append((ex, ey))
            return
        for k in (-1, 1):
            root(r, ex, ey, a + k * spread + r.uniform(-0.12, 0.12), L * r.uniform(0.7, 0.8), depth - 1, spread * 0.9, m)

    # the trunk: six strands, twisting round each other as they climb
    top, base = 176, 270
    strands = []
    for s in range(6):
        ph = s * TAU / 6
        pts = []
        for i in range(31):
            t = i / 30
            y = base - (base - top) * t
            w = 15 - 8 * math.sin(math.pi * t) + 2 * t          # waisted: wide at the foot, flaring at the crown
            pts.append((cx + w * math.sin(ph + t * TAU * 0.9), y))
        strands.append(pts)
        d = "M" + " L".join("%s %s" % (f(px), f(py)) for px, py in pts)
        seg(6, d)
    # each strand's top grows into a limb; each strand's foot into a root
    # limbs, left half (angles measured on the left; the right mirrors them)
    order = sorted(range(6), key=lambda s: strands[s][-1][0])
    for k, (deg, L) in enumerate(((-168, 32), (-136, 36), (-108, 38))):
        seed = rng.random()
        for m, s in ((1, order[k]), (-1, order[5 - k])):
            x, y = strands[s][-1]
            branch(random.Random(seed), x, y, math.radians(deg), L, 5, 0.46, m)
    # four strands' feet become the three great roots (the middle pair meet)
    wells = []
    order = sorted(range(6), key=lambda s: strands[s][0][0])
    for k, (deg, L) in enumerate(((150, 30), (104, 34))):
        seed = rng.random()
        for m, s in ((1, order[[0, 2][k]]), (-1, order[[5, 3][k]])):
            x, y = strands[s][0]
            ang = turn(math.radians(deg), m)
            ex, ey, d = curve(x, y, ang, L, 0.12 * m)
            lines["r4"] = lines.get("r4", "") + d
            if k == 0 or m > 0:
                wells.append((ex, ey) if k == 0 else (cx, ey + 4))
            for j in (-1, 1):
                root(random.Random(seed + j), ex, ey, math.radians(deg) + j * 0.5, 22, 3, 0.55, m)

    # motes of light in the crown
    for _ in range(90):
        r = math.sqrt(rng.random()) * 0.95
        a = rng.uniform(-math.pi + 0.05, -0.05)
        motes.append((CX + RX * r * math.cos(a), CY + RY * r * math.sin(a)))

    widths = {6: ("2.2", ".95"), 5: ("3", ".95"), 4: ("2.3", ".92"), 3: ("1.7", ".88"), 2: ("1.25", ".82"), 1: (".95", ".75"), 0: (".75", ".65"),
              "r4": ("2.6", ".9"), "r3": ("1.9", ".85"), "r2": ("1.4", ".8"), "r1": ("1", ".72"), "r0": (".8", ".6")}
    tree = []
    for k in [6, 5, 4, 3, 2, 1, 0, "r4", "r3", "r2", "r1", "r0"]:
        if k not in lines:
            continue
        w, o = widths[k]
        colour = TEAL if str(k).startswith("r") else MINT
        tree.append('<path d="%s" fill="none" stroke="%s" stroke-width="%s" stroke-linecap="round" opacity="%s"/>' % (lines[k], colour, w, o))
        if k in (6, 5, 4, "r4", "r3"):
            glow.append('<path d="%s" fill="none" stroke="%s" stroke-width="%s"/>' % (lines[k], colour, f(float(w) + 2)))

    # ── the nine realms: hexagons, joined like a network ──
    realms = {
        "asgard": (200, 52), "alfheim": (124, 84), "vanaheim": (276, 84),
        "jotunheim": (68, 214), "muspelheim": (332, 214), "midgard": (200, 222),
        "svartalfheim": (110, 312), "niflheim": (290, 312), "hel": (200, 350),
    }
    links = [("asgard", "alfheim"), ("asgard", "vanaheim"), ("alfheim", "jotunheim"), ("vanaheim", "muspelheim"),
             ("asgard", "midgard"), ("jotunheim", "midgard"), ("muspelheim", "midgard"), ("midgard", "svartalfheim"),
             ("midgard", "niflheim"), ("svartalfheim", "hel"), ("niflheim", "hel")]
    net = "".join("M%s %sL%s %s" % (realms[a] + realms[b]) for a, b in links)
    out.append('<path d="%s" stroke="%s" stroke-width="1" stroke-dasharray="2 4" opacity=".45"/>' % (net, TEAL))
    out += tree
    hexes, cores, halos = "", "", ""
    for name, (x, y) in realms.items():
        r = 8.5 if name in ("asgard", "midgard") else 6.5
        pts = " ".join("%s,%s" % (f(x + r * math.cos(math.radians(60 * i - 90))), f(y + r * math.sin(math.radians(60 * i - 90)))) for i in range(6))
        hexes += '<polygon points="%s"/>' % pts
        cores += '<circle cx="%s" cy="%s" r="%s"/>' % (f(x), f(y), "3" if r > 7 else "2.2")
        halos += '<circle cx="%s" cy="%s" r="%s"/>' % (f(x), f(y), f(r * 2))
    for x, y in wells:                                        # the three wells: rings on the roots
        halos += '<circle cx="%s" cy="%s" r="11"/>' % (f(x), f(y))
        hexes += '<circle cx="%s" cy="%s" r="5.5"/><circle cx="%s" cy="%s" r="9" stroke-dasharray="2 2.6"/>' % (f(x), f(y), f(x), f(y))
        cores += '<circle cx="%s" cy="%s" r="2"/>' % (f(x), f(y))
    out.append('<g fill="%s" opacity=".14">%s</g>' % (MINT, halos))
    out.append('<g fill="#14181c" fill-opacity=".85" stroke="%s" stroke-width="1.5">%s</g>' % (MINT_HOT, hexes))
    out.append('<g fill="%s">%s</g>' % (MINT_HOT, cores))
    glow.append('<g fill="%s">%s</g>' % (MINT_HOT, cores))

    # tips, leaves and motes
    dots = "".join('<circle cx="%s" cy="%s" r="%s"/>' % (f(x), f(y), f(rng.uniform(1.3, 2.3))) for x, y in tips)
    leaves = ""                                               # leaves round the tips and the last forks: a canopy, not a fringe
    for x, y in tips + joints:
        for _ in range(2 if rng.random() < 0.5 else 1):
            a, r = rng.uniform(0, TAU), rng.uniform(3, 8)
            if inside(x + r * math.cos(a), y + r * math.sin(a)):
                leaves += '<circle cx="%s" cy="%s" r="%s"/>' % (f(x + r * math.cos(a)), f(y + r * math.sin(a)), f(rng.uniform(0.6, 1.2)))
    mote = "".join('<circle cx="%s" cy="%s" r="%s" opacity="%s"/>' % (f(x), f(y), f(rng.uniform(0.5, 1.1)), f(rng.uniform(0.25, 0.6))) for x, y in motes)
    rdots = "".join('<circle cx="%s" cy="%s" r="%s"/>' % (f(x), f(y), f(rng.uniform(1, 1.7))) for x, y in rtips)
    out.append('<g fill="%s">%s</g><g fill="%s" opacity=".6">%s</g><g fill="%s">%s</g><g fill="%s" opacity=".85">%s</g>' % (
        MINT_HOT, dots, MINT, leaves, MINT_HOT, mote, TEAL, rdots))
    glow.append('<g fill="%s">%s</g>' % (MINT_HOT, dots))

    defs = GLOW.replace("SD", "3") + (
            '<radialGradient id="aura"><stop offset="0" stop-color="%s" stop-opacity=".2"/><stop offset=".6" stop-color="%s" stop-opacity=".06"/>'
            '<stop offset="1" stop-color="%s" stop-opacity="0"/></radialGradient>'
            '<linearGradient id="horizon"><stop offset="0" stop-color="%s" stop-opacity="0"/><stop offset=".5" stop-color="%s" stop-opacity=".7"/>'
            '<stop offset="1" stop-color="%s" stop-opacity="0"/></linearGradient>') % (MINT, MINT, MINT, MINT, MINT, MINT)
    body = '<g filter="url(#glow)" opacity=".6">%s</g>%s' % ("".join(glow), "".join(out))
    return doc(W, H, "Yggdrasil, the nine realms and the Elder Futhark, inside a HUD ring.", body, defs)


# ── the logo ──────────────────────────────────────────────────────────────────
def logo():
    """Yggdrasil as an emblem: a dome of forking branches over the trunk, the
    roots spread below, a lit node at every tip (the Yggdrasil card's circuit
    tree, drawn bold enough to read at 34px), in a ring. Symmetric — an
    emblem, not a sketch — so nothing here is random."""
    lines, nodes = [], []

    def grow(x, y, a, length, depth, fork, k):
        x2, y2 = x + length * math.cos(a), y + length * math.sin(a)
        lines.append((x, y, x2, y2, min(depth + 1, 3)))
        if depth == 0:
            nodes.append((x2, y2))
            return
        for da in fork:
            grow(x2, y2, a + math.radians(da), length * k, depth - 1, fork, k)

    up, down = -math.pi / 2, math.pi / 2
    lines.append((32, 45, 32, 28, 3))                       # the trunk
    for da in (-44, 0, 44):                                 # the crown: three limbs, forking twice
        grow(32, 28, up + math.radians(da), 7.5, 2, (-27, 27), 0.7)
    for da in (-72, 72):                                    # the low boughs
        grow(32, 34, up + math.radians(da), 8.5, 1, (-22, 22), 0.72)
    for da in (-70, -30, 30, 70):                           # the roots
        grow(32, 45, down + math.radians(da), 5.5, 1, (-26, 26), 0.75)

    width = {3: "3.4", 2: "2.4", 1: "1.9"}
    by = {}
    for x, y, x2, y2, w in lines:
        by.setdefault(w, []).append("M%s %sL%s %s" % (f(x), f(y), f(x2), f(y2)))
    tree = "".join('<path d="%s" stroke="%s" stroke-width="%s"/>' % ("".join(d), MINT_HOT, width[w]) for w, d in sorted(by.items()))
    glow = "".join("".join(d) for d in by.values())
    dots = "".join('<circle cx="%s" cy="%s" r="1.6"/>' % (f(x), f(y)) for x, y in nodes)
    body = ('<g filter="url(#glow)" opacity=".7"><circle cx="32" cy="32" r="28.5" fill="none" stroke="%s" stroke-width="3"/>'
            '<path d="%s" stroke="%s" stroke-width="4"/></g>'
            '<circle cx="32" cy="32" r="28.5" fill="%s" stroke="%s" stroke-width="2.4"/>'
            '<circle cx="32" cy="32" r="25.3" fill="none" stroke="%s" stroke-width="1" opacity=".7" stroke-dasharray="1.5 2.6"/>'
            '<g fill="none" stroke-linecap="round" stroke-linejoin="round">%s</g><g fill="%s">%s</g>') % (
        MINT, glow, MINT, LOGO_DARK, MINT, TEAL, tree, MINT, dots)
    return doc(64, 64, "Yggdrasil: Asgard's logo.", body, GLOW.replace("SD", "2"))


# ── icons: 24×24 strokes, used as CSS masks ───────────────────────────────────
ICONS = {
    # the cards
    "server": "<rect x='3' y='4' width='18' height='7' rx='1'/><rect x='3' y='13' width='18' height='7' rx='1'/><path d='M7 7.5h.01M7 16.5h.01M11 7.5h6M11 16.5h6'/>",
    "storage": "<ellipse cx='12' cy='5.5' rx='8' ry='2.8'/><path d='M4 5.5v13c0 1.5 3.6 2.8 8 2.8s8-1.3 8-2.8v-13M4 12c0 1.5 3.6 2.8 8 2.8s8-1.3 8-2.8'/>",
    "network": "<circle cx='12' cy='5' r='2.2'/><circle cx='5' cy='18' r='2.2'/><circle cx='19' cy='18' r='2.2'/><path d='M11 7l-5 9M13 7l5 9M7.2 18h9.6'/>",
    "services": "<rect x='4' y='4' width='6.5' height='6.5'/><rect x='13.5' y='4' width='6.5' height='6.5'/><rect x='4' y='13.5' width='6.5' height='6.5'/><rect x='13.5' y='13.5' width='6.5' height='6.5'/>",
    "clock": "<circle cx='12' cy='12' r='9'/><path d='M12 7v5l3.5 2'/>",
    "music": "<path d='M9 18V5l11-2v13'/><circle cx='6' cy='18' r='3'/><circle cx='17' cy='16' r='3'/>",
    "download": "<path d='M12 3v12M7 10l5 5 5-5M4 20h16'/>",
    "tree": "<path d='M12 21v-9M12 12L7 8M12 12l5-4M12 8V3M7 8L4 6M17 8l3-2M12 21l-4 1.5M12 21l4 1.5'/><circle cx='12' cy='3' r='.6'/>",
    "tv": "<rect x='3' y='5' width='18' height='12' rx='1'/><path d='M8 21h8M12 17v4'/>",
    "stream": "<rect x='3' y='4' width='18' height='12' rx='1'/><path d='M10 7.5l5 2.5-5 2.5zM8 20h8'/>",
    "play": "<path d='M7 4l13 8-13 8z'/>",
    "activity": "<path d='M4 6h16M4 12h16M4 18h10'/>",
    "bulb": "<path d='M9 18h6M10 21h4M12 3a6 6 0 0 0-4 10.5c.7.7 1 1.5 1 2.5h6c0-1 .3-1.8 1-2.5A6 6 0 0 0 12 3z'/>",
    "bolt": "<path d='M13 2L4 14h7l-1 8 9-12h-7z'/>",
    "plug": "<path d='M9 2v6M15 2v6M6 8h12v3a6 6 0 0 1-12 0zM12 17v5'/>",
    "coins": "<path d='M12 3v18M16 7.5c0-1.9-1.8-3-4-3s-4 1.1-4 3 1.8 2.7 4 3.2 4 1.3 4 3.3-1.8 3-4 3-4-1.1-4-3'/>",
    "wifi": "<path d='M2 9a15 15 0 0 1 20 0M5.5 12.5a10 10 0 0 1 13 0M9 16a5 5 0 0 1 6 0M12 19.5h.01'/>",
    "terminal": "<rect x='3' y='4' width='18' height='16' rx='1'/><path d='M7 9l3 3-3 3M12 15h5'/>",
    # the host's facts
    "uptime": "<circle cx='12' cy='13' r='8'/><path d='M12 9v4l3 2M10 2h4M12 2v3'/>",
    "load": "<path d='M3 12h4l3-8 4 16 3-8h4'/>",
    "memory": "<rect x='7' y='7' width='10' height='10'/><path d='M10 3v4M14 3v4M10 17v4M14 17v4M3 10h4M3 14h4M17 10h4M17 14h4'/>",
    "swap": "<path d='M4 8h14l-3-3M20 16H6l3 3'/>",
    "nvme": "<path d='M12 3a2 2 0 0 0-2 2v9.5a4 4 0 1 0 4 0V5a2 2 0 0 0-2-2z'/>",
    "fan": "<circle cx='12' cy='12' r='2'/><path d='M12 10c0-4 2-7 5-7 0 3-2 5-5 7zM14 12c4 0 7 2 7 5-3 0-5-2-7-5zM12 14c0 4-2 7-5 7 0-3 2-5 5-7zM10 12c-4 0-7-2-7-5 3 0 5 2 7 5z'/>",
}


def icon_url(body):
    svg = ("<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='#000' stroke-width='1.8' "
           "stroke-linecap='round' stroke-linejoin='round'>%s</svg>") % body
    return 'url("data:image/svg+xml,%s")' % svg.replace("#", "%23").replace("<", "%3C").replace(">", "%3E").replace('"', "'")


def main(out, ver):
    os.makedirs(out, exist_ok=True)
    q = "?v=" + ver if ver else ""
    files = {
        "frame.svg": frame(),
        "grid.svg": grid(random.Random(3)),
        "forest.svg": forest(random.Random(11)),
        "ygg.svg": ygg(random.Random(7)),
        "logo.svg": logo(),
    }
    for name, body in files.items():
        open(os.path.join(out, name), "w").write(body)
    tpl = {}
    for key in ("frame", "ygg", "logo"):
        t = files[key + ".svg"]
        for colour, mark in ((MINT_HOT, "__H__"), (MINT, "__A__"), (TEAL, "__B__"), (LOGO_DARK, "__D__")):
            t = t.replace(colour, mark)
        tpl[key] = t
    open(os.path.join(out, "tpl.js"), "w").write(
        "// tpl.js — GENERATED by Resources/Glance/hud.py: the HUD's coloured artwork as templates, for theme.js.\n"
        "window.HUD_TPL = " + json.dumps(tpl, separators=(",", ":")) + ";\n")
    css = ["/* hud.css — GENERATED by Resources/Glance/hud.py: the HUD pieces and the icon set. asgard.css draws them. */",
           ":root {"]
    for var, name in (("frame", "frame.svg"), ("grid", "grid.svg"), ("forest", "forest.svg"), ("ygg", "ygg.svg")):
        css.append('  --h-%s: url("/assets/hud/%s%s");' % (var, name, q))
    for name, body in ICONS.items():
        css.append("  --ic-%s: %s;" % (name, icon_url(body)))
    css.append("}")
    open(os.path.join(out, "hud.css"), "w").write("\n".join(css) + "\n")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    main(sys.argv[1], sys.argv[2] if len(sys.argv) > 2 else "")
