#!/usr/bin/env python3
"""hud.py — the Asgard dashboard's HUD, generated.

    hud.py OUTDIR [VERSION]

Writes the pieces asgard.css draws the dashboard's tech-HUD look with:

    frame.svg    the panel frame round every card: a chamfered neon outline
                 (top-left and bottom-right corners cut), a soft glow, bright
                 corner brackets, and small readout marks in the corners. A
                 9-slice border-image (FC-px corners, straight edges that
                 STRETCH — nothing on an edge, so any card size is exact)
    grid.svg     the page's ground: a faint grid with circuit traces, one
                 seamless tile that REPEATS down the page — however long a
                 page is, the backdrop never runs out (a single big image did)
    forest.svg   misty pine ridges, three layers in teal fog; pinned to the
                 bottom of the screen (a fixed layer, not a fixed background,
                 so phones honour it too), tiles left-right
    ygg.svg      Yggdrasil in line art — a branching circuit tree, roots
                 below, nodes at its tips — inside a ticked HUD ring
    logo.svg     the angular "A" in a shield: the header logo and tab icon
    hud.css      the URLs (with VERSION, so Glance's 2 h asset cache never
                 serves an old piece) and the icon set, as custom properties:
                 --h-frame --h-grid --h-forest --h-ygg, --ic-<name>

Every random choice is seeded, so every build draws the same HUD. Colours:
mint #3be8a8 and teal #1fc8c4 on near-black green.
"""
import math
import os
import random
import sys

TAU = 2 * math.pi
MINT, MINT_HOT, TEAL = "#3be8a8", "#8dffd6", "#1fc8c4"
PREC = [1]


def f(v):
    if PREC[0] == 0:
        s = "%d" % round(v)
    else:
        s = "%.1f" % v
        if s.endswith(".0"):
            s = s[:-2]
    return "0" if s == "-0" else s


def rnd(v):
    return round(v, PREC[0])


def nums(vals):
    out = ""
    for v in vals:
        t = f(v)
        out += t if (not out or t[0] == "-") else " " + t
    return out


def poly_d(pts, close=True):
    """A polyline in relative coordinates, each step from the ROUNDED previous
    point, so rounding never drifts."""
    cx, cy = rnd(pts[0][0]), rnd(pts[0][1])
    d = "M" + nums((cx, cy)) + "l"
    vals = []
    for x, y in pts[1:]:
        nx, ny = rnd(x), rnd(y)
        if nx == cx and ny == cy:
            continue
        vals += [nx - cx, ny - cy]
        cx, cy = nx, ny
    return d + nums(vals) + ("z" if close else "")


def doc(w, h, note, body, defs="", par=""):
    return ('<svg xmlns="http://www.w3.org/2000/svg" width="%d" height="%d" viewBox="0 0 %d %d"%s><!-- %s Generated by hud.py — '
            'see its header. --><defs>%s</defs>%s</svg>') % (w, h, w, h, par, note, defs, body)


GLOW = '<filter id="glow" x="-20%" y="-20%" width="140%" height="140%"><feGaussianBlur stdDeviation="SD"/></filter>'


# ── the panel frame ───────────────────────────────────────────────────────────
FC = 56          # corner slice
FK = 14          # chamfer at top-left and bottom-right


def frame():
    S, o, K = 2 * FC + 64, 1.5, FK
    outline = "M%s %sH%sV%sL%s %sH%sV%sZ" % (f(o + K), f(o), f(S - o), f(S - o - K), f(S - o - K), f(S - o), f(o), f(o + K))
    brackets = ("M%s %sV%sL%s %sH%s" % (f(o), f(o + K + 18), f(o + K), f(o + K), f(o), f(o + K + 18)) +
                "M%s %sH%sV%s" % (f(S - o - 22), f(o), f(S - o), f(o + 22)) +
                "M%s %sV%sL%s %sH%s" % (f(S - o), f(S - o - K - 18), f(S - o - K), f(S - o - K), f(S - o), f(S - o - K - 18)) +
                "M%s %sH%sV%s" % (f(o + 22), f(S - o), f(o), f(S - o - 22)))
    # readouts: three bars after the top-left bracket, ticks down the top-right,
    # a second chamfer line inside the bottom-right, a notch at the bottom-left
    marks = "".join('<rect x="%s" y="%s" width="4" height="2"/>' % (f(o + K + 24 + i * 6), f(o + 3.5)) for i in range(3))
    ticks = "".join("M%s %sh4" % (f(S - o - 7), f(o + 28 + i * 5)) for i in range(4))
    inner = "M%s %sL%s %s" % (f(S - o - 5), f(S - o - K - 6), f(S - o - K - 6), f(S - o - 5))
    notch = "M%s %sl6 0l-6 -6z" % (f(o + 3), f(S - o - 3))
    body = ('<path d="%s" fill="none" stroke="%s" stroke-width="5" opacity=".22" filter="url(#glow)"/>'
            '<path d="%s" fill="none" stroke="%s" stroke-width="1.1" opacity=".6"/>'
            '<path d="%s" fill="none" stroke="%s" stroke-width="5" opacity=".35" filter="url(#glow)"/>'
            '<path d="%s" fill="none" stroke="%s" stroke-width="2.2" stroke-linecap="square"/>'
            '<g fill="%s" opacity=".85">%s</g>'
            '<path d="%s" stroke="%s" stroke-width="1" opacity=".7"/>'
            '<path d="%s" stroke="%s" stroke-width="1" opacity=".55"/>'
            '<path d="%s" fill="%s" opacity=".7"/>') % (
        outline, MINT, outline, MINT, brackets, MINT, brackets, MINT_HOT, MINT, marks, ticks, MINT, inner, MINT, notch, MINT)
    return doc(S, S, "The panel frame round every card: a 9-slice border image (%dpx corners, stretched edges)." % FC,
               body, GLOW.replace("SD", "2.2"))


# ── the page's ground: grid + circuit traces, one seamless tile ───────────────
def grid(rng):
    T = 480
    body = ['<path d="%s" stroke="%s" stroke-width="1" opacity=".045" fill="none"/>' % (
        "".join("M%d 0V%d" % (x, T) for x in range(0, T, 40)) + "".join("M0 %dH%d" % (y, T) for y in range(0, T, 40)), MINT)]
    plus = "".join("M%d %dh6M%d %dv6" % (x - 3, y, x, y - 3) for x in range(40, T, 80) for y in range(40, T, 80) if rng.random() < 0.6)
    body.append('<path d="%s" stroke="%s" stroke-width="1" opacity=".1"/>' % (plus, MINT))
    # circuit traces: walked on the grid's 8px lattice, right angles and 45s,
    # kept clear of the tile's edge so the tile joins seamlessly
    traces, pads = "", ""
    for _ in range(9):
        x, y = rng.randrange(3, T // 8 - 3) * 8, rng.randrange(3, T // 8 - 3) * 8
        pts = [(x, y)]
        d = rng.choice([(1, 0), (0, 1), (-1, 0), (0, -1)])
        for _ in range(rng.randint(3, 6)):
            n = rng.randint(2, 6)
            x, y = x + d[0] * 8 * n, y + d[1] * 8 * n
            x, y = max(16, min(T - 16, x)), max(16, min(T - 16, y))
            pts.append((x, y))
            d = rng.choice([(d[1], d[0]), (-d[1], -d[0]), (d[0] or 1, d[1] or 1)])
            d = (max(-1, min(1, d[0])), max(-1, min(1, d[1])))
        traces += "M" + "L".join("%d %d" % p for p in pts)
        for px, py in (pts[0], pts[-1]):
            pads += '<circle cx="%d" cy="%d" r="2.2"/>' % (px, py)
    body.append('<path d="%s" stroke="%s" stroke-width="1" opacity=".06" fill="none"/>' % (traces, MINT))
    body.append('<g fill="none" stroke="%s" stroke-width="1" opacity=".1">%s</g>' % (MINT, pads))
    return doc(T, T, "The page's ground: grid and circuit traces, one seamless tile.", "".join(body))


# ── misty pines along the foot of the screen ─────────────────────────────────
TW, TH = 1600, 420


def spruce(x, base, h, w, rng, tier=7.0):
    top = base - h
    tiers = max(6, int(h / tier))
    R, L = [], []
    for sd, out in ((1, R), (-1, L)):
        for i in range(tiers):
            t = (i + 0.6) / tiers
            y = top + h * 0.05 + t * h * 0.88
            half = w * (0.05 + 0.95 * t ** 0.92) * rng.uniform(0.62, 1.08)
            droop = h * 0.01 + half * 0.2
            out.append((x + sd * half * rng.uniform(0.18, 0.42), y - droop * 0.2))
            out.append((x + sd * half * rng.uniform(0.62, 0.8), y + droop * 0.35))
            out.append((x + sd * half, y + droop))
            out.append((x + sd * half * rng.uniform(0.74, 0.9), y + droop * 0.8))
    return poly_d([(x, top - h * 0.04)] + R + [(x + w * 0.06, base), (x - w * 0.06, base)] + L[::-1])


def forest(rng):
    PREC[0] = 0
    try:
        out = []
        layers = [(40, (110, 180), "#1a5a48", ".5", 11), (26, (170, 270), "#0f3d31", ".8", 8), (14, (260, 380), "#06201a", "1", 7)]
        for li, (n, (h0, h1), col, op, tier) in enumerate(layers):
            items = []
            for i in range(n):
                x = (i + rng.uniform(-0.4, 0.4)) * TW / n
                h = rng.uniform(h0, h1)
                d = spruce(x, TH + 4, h, h * 0.3, rng, tier)
                items.append(d)
                if x < 120:
                    items.append(spruce(x + TW, TH + 4, h, h * 0.3, random.Random(int(x * 13)), tier))
                if x > TW - 120:
                    items.append(spruce(x - TW, TH + 4, h, h * 0.3, random.Random(int(x * 13)), tier))
            out.append('<path d="%s" fill="%s" opacity="%s"/>' % ("".join(items), col, op))
            if li < 2:
                out.append('<rect y="%d" width="%d" height="180" fill="url(#mist)"/>' % (TH - 230 + li * 70, TW))
        defs = ('<linearGradient id="mist" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="%s" stop-opacity="0"/>'
                '<stop offset=".55" stop-color="%s" stop-opacity=".13"/><stop offset="1" stop-color="%s" stop-opacity="0"/></linearGradient>') % (MINT, MINT, MINT)
        return doc(TW, TH, "Misty pines along the foot of the screen; tiles left-right.", "".join(out), defs,
                   ' preserveAspectRatio="xMidYMax slice"')
    finally:
        PREC[0] = 1


# ── Yggdrasil, in line art ────────────────────────────────────────────────────
def ygg(rng):
    W = H = 400
    cx, cy, R = 200, 200, 186
    out = []
    # the ring: two circles, ticks every 3°, longer every 30°, four bracket arcs
    ticks = ""
    for i in range(120):
        a = TAU * i / 120
        l = 9 if i % 10 == 0 else 4
        ticks += "M%s %sL%s %s" % (f(cx + (R - 2) * math.cos(a)), f(cy + (R - 2) * math.sin(a)), f(cx + (R - 2 - l) * math.cos(a)), f(cy + (R - 2 - l) * math.sin(a)))
    out.append('<circle cx="%d" cy="%d" r="%d" fill="none" stroke="%s" stroke-width="1" opacity=".5"/>' % (cx, cy, R, MINT))
    out.append('<circle cx="%d" cy="%d" r="%d" fill="none" stroke="%s" stroke-width="1" opacity=".25" stroke-dasharray="2 6"/>' % (cx, cy, R - 22, MINT))
    out.append('<path d="%s" stroke="%s" stroke-width="1.2" opacity=".55"/>' % (ticks, MINT))
    arcs = ""
    for k in range(4):
        a0, a1 = TAU * (k / 4 + 0.03), TAU * (k / 4 + 0.22)
        arcs += "M%s %sA%d %d 0 0 1 %s %s" % (f(cx + (R + 6) * math.cos(a0)), f(cy + (R + 6) * math.sin(a0)), R + 6, R + 6,
                                               f(cx + (R + 6) * math.cos(a1)), f(cy + (R + 6) * math.sin(a1)))
    out.append('<path d="%s" fill="none" stroke="%s" stroke-width="2.4" opacity=".85"/>' % (arcs, MINT))
    # the tree: branches split as they climb, roots as they sink; strokes taper
    # with depth; every tip a lit node
    lines, nodes = {}, []

    def grow(x, y, a, L, w, depth, spread, down=False):
        ex, ey = x + L * math.cos(a), y + L * math.sin(a)
        mx, my = (x + ex) / 2 + rng.uniform(-3, 3), (y + ey) / 2 + rng.uniform(-3, 3)
        key = round(w, 1)
        lines[key] = lines.get(key, "") + "M%s %sQ%s %s %s %s" % (f(x), f(y), f(mx), f(my), f(ex), f(ey))
        if depth == 0:
            nodes.append((ex, ey))
            return
        kids = 3 if (depth > 3 and rng.random() < 0.35) else 2
        for k in range(kids):
            off = (k - (kids - 1) / 2) * spread + rng.uniform(-0.12, 0.12)
            na = a + off
            if not down:   # a dome: branches arch out and over, never droop below level
                na = max(-math.pi + 0.22, min(-0.22, na))
            grow(ex, ey, na, L * rng.uniform(0.7, 0.8), max(0.7, w * 0.7), depth - 1, spread * 0.95, down)

    base = cy + 70
    # trunk: several strands braided up the middle
    for s in (-6, -2, 2, 6):
        lines[3.2] = lines.get(3.2, "") + "M%s %sC%s %s %s %s %s %s" % (
            f(cx + s), f(base), f(cx + s * 1.6), f(base - 40), f(cx - s * 0.6), f(base - 75), f(cx + s * 0.3), f(base - 105))
    for k, a in enumerate((-math.pi / 2 - 1.15, -math.pi / 2 - 0.6, -math.pi / 2 - 0.05, -math.pi / 2 + 0.55, -math.pi / 2 + 1.12)):
        grow(cx + (k - 2) * 2, base - 100 + (6 if k in (0, 4) else 0), a, 36 if k in (1, 2, 3) else 30, 2.6, 5, 0.5)
    for a in (math.pi / 2 - 1.05, math.pi / 2 - 0.4, math.pi / 2 + 0.4, math.pi / 2 + 1.05):
        grow(cx, base, a, 26, 2.4, 3, 0.7, down=True)
    for w, d in lines.items():
        out.append('<path d="%s" fill="none" stroke="%s" stroke-width="%s" stroke-linecap="round" opacity=".9"/>' % (d, MINT, f(w)))
    node = "".join('<circle cx="%s" cy="%s" r="%s"/>' % (f(x), f(y), f(rng.uniform(1.4, 2.4))) for x, y in nodes if math.hypot(x - cx, y - cy) < R - 26)
    out.append('<g fill="%s">%s</g>' % (MINT_HOT, node))
    body = '<g filter="url(#glow)" opacity=".55">%s</g>%s' % ("".join(out), "".join(out))
    return doc(W, H, "Yggdrasil in line art inside a HUD ring.", body, GLOW.replace("SD", "3"))


# ── the logo ──────────────────────────────────────────────────────────────────
def logo():
    shield = "M32 3L58 14V34C58 47 46 57 32 61C18 57 6 47 6 34V14Z"
    a = "M18 47L32 13L46 47M24 36H40"
    chev = "M27 47L32 37L37 47"
    body = ('<g filter="url(#glow)" opacity=".7"><path d="%s" fill="none" stroke="%s" stroke-width="3"/><path d="%s" fill="none" stroke="%s" stroke-width="5"/></g>'
            '<path d="%s" fill="#06231a" stroke="%s" stroke-width="2.2"/>'
            '<path d="%s" fill="none" stroke="%s" stroke-width="4.2" stroke-linejoin="miter" stroke-linecap="square"/>'
            '<path d="%s" fill="none" stroke="%s" stroke-width="2"/>') % (shield, MINT, a, MINT, shield, MINT, a, MINT_HOT, chev, TEAL)
    return doc(64, 64, "The angular A: Asgard's logo.", body, GLOW.replace("SD", "2"))


# ── icons: 24×24 strokes, used as CSS masks ───────────────────────────────────
ICONS = {
    # the cards
    "server": "<rect x='3' y='4' width='18' height='7' rx='1'/><rect x='3' y='13' width='18' height='7' rx='1'/><path d='M7 7.5h.01M7 16.5h.01M11 7.5h6M11 16.5h6'/>",
    "storage": "<ellipse cx='12' cy='5.5' rx='8' ry='2.8'/><path d='M4 5.5v13c0 1.5 3.6 2.8 8 2.8s8-1.3 8-2.8v-13M4 12c0 1.5 3.6 2.8 8 2.8s8-1.3 8-2.8'/>",
    "network": "<circle cx='12' cy='5' r='2.2'/><circle cx='5' cy='18' r='2.2'/><circle cx='19' cy='18' r='2.2'/><path d='M11 7l-5 9M13 7l5 9M7.2 18h9.6'/>",
    "services": "<rect x='4' y='4' width='6.5' height='6.5'/><rect x='13.5' y='4' width='6.5' height='6.5'/><rect x='4' y='13.5' width='6.5' height='6.5'/><rect x='13.5' y='13.5' width='6.5' height='6.5'/>",
    "clock": "<circle cx='12' cy='12' r='9'/><path d='M12 7v5l3.5 2'/>",
    "music": "<path d='M9 18V5l11-2v13'/><circle cx='6' cy='18' r='3'/><circle cx='17' cy='16' r='3'/>",
    "download": "<path d='M12 3v12M7 10l5 5 5-5M4 20h16'/>",
    "tree": "<path d='M12 21v-9M12 12L7 8M12 12l5-4M12 8V3M7 8L4 6M17 8l3-2M12 21l-4 1.5M12 21l4 1.5'/><circle cx='12' cy='3' r='.6'/>",
    "tv": "<rect x='3' y='5' width='18' height='12' rx='1'/><path d='M8 21h8M12 17v4'/>",
    "stream": "<rect x='3' y='4' width='18' height='12' rx='1'/><path d='M10 7.5l5 2.5-5 2.5zM8 20h8'/>",
    "play": "<path d='M7 4l13 8-13 8z'/>",
    "activity": "<path d='M4 6h16M4 12h16M4 18h10'/>",
    "bulb": "<path d='M9 18h6M10 21h4M12 3a6 6 0 0 0-4 10.5c.7.7 1 1.5 1 2.5h6c0-1 .3-1.8 1-2.5A6 6 0 0 0 12 3z'/>",
    "bolt": "<path d='M13 2L4 14h7l-1 8 9-12h-7z'/>",
    "plug": "<path d='M9 2v6M15 2v6M6 8h12v3a6 6 0 0 1-12 0zM12 17v5'/>",
    "coins": "<path d='M12 3v18M16 7.5c0-1.9-1.8-3-4-3s-4 1.1-4 3 1.8 2.7 4 3.2 4 1.3 4 3.3-1.8 3-4 3-4-1.1-4-3'/>",
    "wifi": "<path d='M2 9a15 15 0 0 1 20 0M5.5 12.5a10 10 0 0 1 13 0M9 16a5 5 0 0 1 6 0M12 19.5h.01'/>",
    "terminal": "<rect x='3' y='4' width='18' height='16' rx='1'/><path d='M7 9l3 3-3 3M12 15h5'/>",
    # the host's facts
    "uptime": "<circle cx='12' cy='13' r='8'/><path d='M12 9v4l3 2M10 2h4M12 2v3'/>",
    "load": "<path d='M3 12h4l3-8 4 16 3-8h4'/>",
    "memory": "<rect x='7' y='7' width='10' height='10'/><path d='M10 3v4M14 3v4M10 17v4M14 17v4M3 10h4M3 14h4M17 10h4M17 14h4'/>",
    "swap": "<path d='M4 8h14l-3-3M20 16H6l3 3'/>",
    "nvme": "<path d='M12 3a2 2 0 0 0-2 2v9.5a4 4 0 1 0 4 0V5a2 2 0 0 0-2-2z'/>",
    "fan": "<circle cx='12' cy='12' r='2'/><path d='M12 10c0-4 2-7 5-7 0 3-2 5-5 7zM14 12c4 0 7 2 7 5-3 0-5-2-7-5zM12 14c0 4-2 7-5 7 0-3 2-5 5-7zM10 12c-4 0-7-2-7-5 3 0 5 2 7 5z'/>",
}


def icon_url(body):
    svg = ("<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='#000' stroke-width='1.8' "
           "stroke-linecap='round' stroke-linejoin='round'>%s</svg>") % body
    return 'url("data:image/svg+xml,%s")' % svg.replace("#", "%23").replace("<", "%3C").replace(">", "%3E").replace('"', "'")


def main(out, ver):
    os.makedirs(out, exist_ok=True)
    q = "?v=" + ver if ver else ""
    files = {
        "frame.svg": frame(),
        "grid.svg": grid(random.Random(3)),
        "forest.svg": forest(random.Random(11)),
        "ygg.svg": ygg(random.Random(7)),
        "logo.svg": logo(),
    }
    for name, body in files.items():
        open(os.path.join(out, name), "w").write(body)
    css = ["/* hud.css — GENERATED by Resources/Glance/hud.py: the HUD pieces and the icon set. asgard.css draws them. */",
           ":root {"]
    for var, name in (("frame", "frame.svg"), ("grid", "grid.svg"), ("forest", "forest.svg"), ("ygg", "ygg.svg")):
        css.append('  --h-%s: url("/assets/hud/%s%s");' % (var, name, q))
    for name, body in ICONS.items():
        css.append("  --ic-%s: %s;" % (name, icon_url(body)))
    css.append("}")
    open(os.path.join(out, "hud.css"), "w").write("\n".join(css) + "\n")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    main(sys.argv[1], sys.argv[2] if len(sys.argv) > 2 else "")
